### ISSUE TITLE
Engine 1 mod, not working.

### ISSUE THREAD

**Issue by dadee971** [lishid/Orebfuscator#104]
Hi,
Engine 2 is working, but i can't make Engine 1 to works: Orebfuscator 4.1.0.
Blocks are still visible with Engine 1.

Here is my config:

http://pastebin.com/9vKMfAgc

**Comment by RoboMWM** [comment]
Please explain what you mean by "blocks are still visible." Do you see any errors in the console log? Engine mode 1 is working perfectly for me with Orebfuscator 4.1.0.

Also, what is your spigot /version

**Comment by dadee971** [comment]
If i use an Xray textures pack i can see all ores.
Engine 2 hides ores, engine 1 also does on 1.9.4, but on spigot 1.10 only engine 2 hide ores.

CraftBukkit version git-Spigot-3ccadba-7f1a322 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

**Comment by ProgrammerDan** [comment]
Ah, I see the confusion.

So, unless DarknessHider is turned on, ores exposed to air will be visible. This is true in both engine mode 1 and 2, but engine mode 2 "disguises" this fact by filling all the visible space with ores and other goodies as set in the config.

If you don't believe me, take a third screenshot from the same location, but with Orebfuscator entirely turned off. You'll notice that all the ores that weren't obfuscated in engine mode 1 were touching air.

**Comment by dadee971** [comment]
I have enable DarknessHider.
I can see the ores like before.

**Comment by ProgrammerDan** [comment]
Hmm, that might indicate a problem with Darkness Hider; depends on the configuration you're using.

Did you do the second test? Shutting off Orebfuscator and observing the ores? You'll see a ton more with Orebfuscator off, as the remaining ores were obfuscated and not touching air.

Basically, the images you showed me are normal operation. Darkness hider should have hidden a few more (but not if the caves are well lit); if it didn't, try clearing the Obfuscation cache; if darkness hider still fails to hide stuff, that's a separate issue we can look into.

**Comment by dadee971** [comment]
With OFC off, i can see the same ores that i see with Engine 1. No more.

**Comment by dadee971** [comment]
Nevermind i'll use Engine 2.
I was always using Engine 1 because it was using less memory and CPU.
But, with this update tit is not working at all, i have the same config that i was using with old version ( for 1.9.4).

**Comment by ProgrammerDan** [comment]
This update seems to be working for others with same or similar settings, unfortunately. 

Can you paste the image with OFC off? And to confirm, disable OFC by renaming the .jar as .jar.off or something similar.

There's still a possibility that something is indeed going wrong here and I've jumped the gun so to speak :).

**Comment by dadee971** [comment]
OFC Engine 1:
http://image.noelshack.com/fichiers/2016/24/1465920176-2016-06-14-18-01-13.png

OFC Off
http://image.noelshack.com/fichiers/2016/24/1465920184-2016-06-14-18-01-57.png
http://image.noelshack.com/fichiers/2016/24/1465920239-ofcoff.jpg

**Comment by ProgrammerDan** [comment]
Hmm, very odd. This new image definitely illustrates some kind of issue. Has your config changed or still as pasted?

**Comment by dadee971** [comment]
No my config it still the same.

**Comment by ProgrammerDan** [comment]
Can you also paste which version of ProtocolLib you are using?

**Comment by dadee971** [comment]
[Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.0.2-SNAPSHOT-b293

**Comment by ProgrammerDan** [comment]
Alright, I'll see if I can reproduce later tonight (not in a position to at the moment).

**Comment by dadee971** [comment]
Thanks for your job :)

**Comment by RoboMWM** [comment]
Hmm, paste permissions also?

**Comment by ProgrammerDan** [comment]
Worth a look although permission and op bypass are disabled in the given config.

**Comment by dadee971** [comment]
I'm op i have all permissions.

**Comment by RoboMWM** [comment]
> I'm op i have all permissions.
 I have test with an no op account and it is the same thing.

Just fyi, you may also have permission nodes from your designated group/assigned for you via your permission plugin, unless you happen not to use one.

**Comment by dadee971** [comment]
I have all permission:

  Owner:
    default: false
    permissions:
    - '*'
    - vanish.*
    - mv.bypass.gamemode.*
    - mv.bypass.playerlimit.*
    info:
      prefix: '&4➲ Owner '
      build: true
      suffix: ''

**Comment by RoboMWM** [comment]
could you add three backticks (\`\`\`) above `Owner` so we can see the raw characters?

Otherwise, I'm assuming you assigned the `*` node, which means you'll have all permissions regardless of op status.

**Comment by dadee971** [comment]
Done.

**Comment by RoboMWM** [comment]
Yea, test with another account or remove yourself from the owner group when testing as a "non-op" player.

Also, see if this happens on a fresh server (new world, no plugins except orebfuscator and protocollib).

**Comment by dadee971** [comment]
On a fresh server, with only Orebfiscator and Protocollib:
same results, engine 1 not working.

**Comment by RoboMWM** [comment]
What spigot/paper /version

**Comment by dadee971** [comment]
CraftBukkit version git-Spigot-3ccadba-7f1a322 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)

**Comment by RoboMWM** [comment]
Sorry, was on mobile and checked your first post. Just really don't know what's going on since it's working on my end. I could disable the cache to see if that might be holding the old working stuff, but other than that I don't have any clue other than perhaps the client saving the ore locations, unless you're using an xray texture pack

**Comment by dadee971** [comment]
I'm using a texture pack.

**Comment by Aleksey-Terzi** [comment]
@dadee971 

I've prepared some demo video to show that for my simple test obfuscation is working ok: https://www.youtube.com/watch?v=88x_QOSu9aQ

What I did:

1) Installed just only two plugins on my 1.10 Spigot server: Orebfuscator4 v4.1.0-SNAPSHOT and ProtocolLib v4.0.2-SNAPSHOT-b293

2) Applied config provided in first post

3) Run server

4) Dig hole, put 4 iron ore and covered it by stone

5) Relogged to clear client's cache

6) Enabled XRay texture pack

7) I don't see iron ore under the stone blocks

8) Disabled Orebfuscator by entering **ofc disable**

9) Relogged to clear client's cache

10) Now I see my 4 iron ore and all sorroundin ores

I would appreciate if you can repeat my steps and show what result you have.

**Comment by dadee971** [comment]
You are true. It is working.
But i can still see the Block that are exposed to air, even if i set: DarknessHideBlocks: true

**Comment by dadee971** [comment]
Forget it, i'll keep going with Engine 2 :)

**Comment by ProgrammerDan** [comment]
For what it's worth, Engine 2 provides ... in general ... better protection :)
