### ISSUE TITLE
API access to toggle player bypass?

### ISSUE THREAD

**Issue by Cryptite** [lishid/Orebfuscator#105]
I'd like to be a little more surgical with how I use Orebfuscator. Is there any chance we devs could get an API hookin to add/remove players to a bypass list that doesn't involve constantly changing permissions? I'd really like to be able to tag certain players in certain circumstances, rather than force all XXX players on the server to be hit by Oreb if only 2 to 3 are mining at any one point in time.

Cheers!

**Comment by ProgrammerDan** [comment]
Thanks for the suggestion! 

Curiosity demands that I ask: what's the advantage of a new custom system when Orebfuscator already supports this via permissions? To my recollection setting permissions programmatically isn't too difficult, even less so if you use a plugin like PermissionEx's direct API calls. Anyway, curious what advantages the direct api route would offer.

**Comment by Cryptite** [comment]
I suppose it's be the (arguably negligible) performance cost of IO. The scale of a very large server that has PEX running winds up tallying a very large flatfile for the stored permissions file. Indeed it might _not_ be a big performance hit, but it is a non-negligible IO hit of adjusting the permissions file frequently with lots of players having that permission added and removed could be cleaner if it was done just through OFC. There could be two modes of the bypass as well with OFC: one that's stored to a file or just an internal UUID list that would get wiped on any reload.

In my case the non-saving version would work fine because I already have events for when players are mining. So I suppose it's more a desire to hook straight into OFC than take a slightly less performant route through PEX...

**Comment by RoboMWM** [comment]
>  I'd really like to be able to tag certain players in certain circumstances, rather than force all XXX players on the server to be hit by Oreb if only 2 to 3 are mining at any one point in time.

I don't see the point in doing this. As said in #paper IRC, someone could be just exploring up top - and y-level wouldn't matter, since the entire chunk is always sent to the client. I'd find this perhaps more intensive since it has to now check for other factors before determining if it should obfuscate the sent chunk or not.

**Comment by Cryptite** [comment]
Well, furthermore, it does seem OFC is pretty performant as I was still
running at 19.9+ TPS last night with around 30 players, so maybe I'm just
making a big todo about nothing.
