### ISSUE TITLE
Command to allow config reload

### ISSUE THREAD

**Issue by marcbal** [lishid/Orebfuscator#107]
Hi,
Can you create a command like `/orebfuscator reload` that reload and apply the new config file, without nécessary restart whole server ?

**Comment by Foulwerp** [comment]
/ofc reload I think is the command for this.

**Comment by ProgrammerDan** [comment]
Indeed! See here: https://github.com/lishid/Orebfuscator/blob/master/Plugin/src/main/resources/plugin.yml#L15 in this case `/ofc reload` is the ticket.

**Comment by marcbal** [comment]
Oww, i think I missused the /help command : `/help orebfuscator` returned no results :/

**Comment by ProgrammerDan** [comment]
Hmm, that's actually a good note. /help ofc would have shown you this answer, but /help orebfuscator won't. I should probably switch that around so that orebfuscator is an alias of ofc or vice-versa.
