### ISSUE TITLE
Darkness Hider does not appear to function in 1.10

### ISSUE THREAD

**Issue by ProgrammerDan** [lishid/Orebfuscator#108]
As reported: https://github.com/lishid/Orebfuscator/issues/104#issuecomment-226535664

**Comment by Foulwerp** [comment]
Looking at the comments and his config it doesn't look like he added ores to the list of blocks hidden by the darkness hider. It appears to be functioning correctly.

**Comment by ProgrammerDan** [comment]
Welp, that would do it! Thanks.
