### ISSUE TITLE
Chest, workbences, furnaces and more turn into stone

### ISSUE THREAD

**Issue by Hampuswe** [lishid/Orebfuscator#112]
When joining the server or coming close to a place you haven't been for a while (Not necessary a unloaded chunk) chest etc. appear like stone (see images) even for people with the bypass permission.

![2016-06-29_20 46 26](https://cloud.githubusercontent.com/assets/13381331/16464760/043a6dc4-3e3c-11e6-8039-271313b0bad1.png)
![2016-06-29_20 46 34](https://cloud.githubusercontent.com/assets/13381331/16464759/04396b72-3e3c-11e6-9217-58bd718ac799.png)

**Comment by Foulwerp** [comment]
This would be the proximity hider to prevent hacked clients to find chests. If you do not want this feature disable proximity hider in the configs.

**Comment by Aleksey-Terzi** [comment]
@Hampuswe

As Foulwerp suggested - behavior you see is ProximityHider.

You have some options on how to disable it for player(s):

1. In config set Booleans.UseProximityHider to False - this will disable ProximityHider for all players
2. If player is Op and Booleans.NoObfuscationForOps = True then ProximityHider will be disabled for such player
3. If permission 'Orebfuscator.deobfuscate' is granted to player  and Booleans.NoObfuscationForPermission = True then ProximityHider will be disabled for such player

**Comment by Hampuswe** [comment]
Thank you! It's all working now!
