### ISSUE TITLE
ChunkReloader high cpu / tick usage

### ISSUE THREAD

**Issue by sigmaroot** [lishid/Orebfuscator#114]
https://timings.aikar.co/v2/?id=70178179c1854a5980b60367125cc3a0&section=lag

As you can see, the actual ChunkReloader (4.1.2) has a huge performance usage.
Any ideas?

Thanks!

**Comment by Foulwerp** [comment]
Can you paste your config.yml so we can see how you have it set up. Also what build of Paper are you using?

**Comment by sigmaroot** [comment]
http://pastebin.com/VDWmcPnn

Here we go...

**Comment by Foulwerp** [comment]
Are players allowed to use WorldEdit? 

I would try disabling orebfuscation in any world that people use WorldEdit a lot. WorldEdit will reload chunks every time it is used and is probably what is causing this problem.

Just add the names of those worlds to the worlds option in the config.

````
  Worlds:
  - world_nether
  - world_the_end
````

**Comment by Aleksey-Terzi** [comment]
@sigmaroot

Thank you for statistics.

Could you please let me know characteristics of your server and how much players played during time when statistics was done?

Also I would appreciate if you can make timing statistics for example during 1 hour, that would be very helpful.

@Foulwerp

Yes, agree, possibly this could be solution.
Orebfuscator's ChunkReloader is not reloading chunk if it is cached.
But if chunk was modified then cached chunk is marked as invalidated.

**Comment by sigmaroot** [comment]
@Aleksey-Terzi 
Thank you for your answer.

Here are some informations about my server:
Players: ~ 62 of 90 slots
Software: git-Paper-809 (MC: 1.10.2) (Implementing API version 1.10.2-R0.1-SNAPSHOT)

GC Output:
Runtime: 4 hours 41 minutes 35 seconds
Actual TPS =  19.82
Max RAM: 18,000 MB
Reserved RAM: 4,048 MB
Free RAM: 1,914 MB
World " world ":  6,384  Chunks,  4,605  Einheiten,  24,762  Tiles.
The End " world_the_end ":  64  Chunks,  14  Einheiten,  22  Tiles.
World " spawn ":  169  Chunks,  31  Einheiten,  431  Tiles.
Nether " world_nether ":  440  Chunks,  72  Einheiten,  486  Tiles.
World " abbauwelt ":  913  Chunks,  236  Einheiten,  268  Tiles.
World " event ":  231  Chunks,  35  Einheiten,  730  Tiles.
World " springfield ":  531  Chunks,  249  Einheiten,  895  Tiles.
World " bauwelt ":  233  Chunks,  7  Einheiten,  80  Tiles.

As you can see, at this moment everything is fine. I'm doing an hour long timing now and I'm going to post it here. But as you can see, after running a while, the server is stable. The first timing (issue opening) was taken just a few minutes after restarting. A lot of players where joining then. Maybe this was causing the TPS drop.

As I said before, I'm doing a long timing but a I guess, everything is fine. Maybe this could be closed / resolved. But if you think, it is too much usage, you can take a look for it.

**Comment by sigmaroot** [comment]
New Timing: https://timings.aikar.co/v2/?id=cadfbf0bf6fa45a0b5fc5958f52a7a7f

Please verify, that this usage of ChunkReloader is "normal"

**Comment by Foulwerp** [comment]
Did you black list the worlds? 

This looks a lot better, and I would think that is in a more reasonable usage for 60-70 players.

**Comment by sigmaroot** [comment]
No I don't, there's no reason for me to blacklist a world.

**Comment by Aleksey-Terzi** [comment]
Thank you very much for this statistics.
I will try to fix this problem.

**Comment by sigmaroot** [comment]
@Aleksey-Terzi 
So, do you think this is too much?

**Comment by Aleksey-Terzi** [comment]
Yes, I think 24% of tick time during lag spike is too much.
I think this could be fixed by distributing chunks to reload more smoothly during the time.

Though 7% of tick time in average is not good number too.
I will try to fix this by improving caching.

**Comment by Foulwerp** [comment]
This server runs multiple worlds on the same server and they are trying to orebfuscator three normal worlds along with a nether and end. The percentages shown for orebfuscator are a combined total for all the worlds, and a single world the vanilla loader uses almost as much as the combined total for orebfuscator. 

Orebfuscating a normal world takes a lot of effort, but add two more on the same server your going to run into high usage. Best way to solve this is disable it on the worlds you don't need it, or bungee your server to spread the load even if you run multiple servers bungeed on the same machine.

While I agree optimization is always good and if this has lead to you doing that awesome, but there are limitations to what you can run on a single server in minecraft without running into huge performance decreases.

**Comment by Foulwerp** [comment]
On phone can't edit previous post but it looks like with his previous post there are 8 worlds total on one server. In general running that many worlds on a single server will destroy your performance, and should be bungeed to spread the load.

**Comment by sigmaroot** [comment]
Thanks for all answers. Yes, we're running a lot of worlds but most of them are just small like lobbys, no more then 200 to 300 chunks. Also, I guess, it depends on the player count and the view distance how many chunks are loaded and must be orebfuscated. You're right, we're at the maximum what's possible on a single machine but it is normally fine, 20 TPS all the time with just ~ 50 players average. I'll try to disable one or two worlds to increase the performance.

Btw: It's terrible to bungee a server with 50 plugins that runs for almost 3-4 years on a single machine xD

Thanks a lot, closed :)
