### ISSUE TITLE
Command /ofc enable/disable worldname not doing anything

### ISSUE THREAD

**Issue by Devillion** [lishid/Orebfuscator#115]
When I type the command for "/ofc enable/disable worldname" nothing happens.

I'm using latest version with spigot 1.10 - i see the command in the console but there are no errors and no messages in chat when I type that command and the world is not added/removed from the config file.

**Comment by Aleksey-Terzi** [comment]
There was mistake on the wiki (which is fixed now).   
Correct usage of command: /ofc \<enable/disable\> **world** \<worldname\>
