### ISSUE TITLE
Spigot 1.7 - 1.8 - none of versions are not working

### ISSUE THREAD

**Issue by Bielecki** [lishid/Orebfuscator#116]
When I install 1.7 versions it says that it not supports 1.8 builds. So I downloaded 1.8 versions, but any of them is not working (3.0.0 - 3.0.6-R3 tested):

> [20:12:26 ERROR]: Error occurred while enabling Orebfuscator3 v3.0.6-R3 (Is it up to date?)
> java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/Block
>         at com.lishid.orebfuscator.internal.MinecraftInternals.isBlockTransparent(MinecraftInternals.java:30) ~[?:?]
>         at com.lishid.orebfuscator.OrebfuscatorConfig.generateTransparentBlocks(OrebfuscatorConfig.java:120) ~[?:?]
>         at com.lishid.orebfuscator.OrebfuscatorConfig.isBlockTransparent(OrebfuscatorConfig.java:105) ~[?:?]
>         at com.lishid.orebfuscator.OrebfuscatorConfig.setBlockValues(OrebfuscatorConfig.java:341) ~[?:?]
>         at com.lishid.orebfuscator.OrebfuscatorConfig.load(OrebfuscatorConfig.java:414) ~[?:?]
>         at com.lishid.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:57) ~[?:?]
>         at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
>         at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
>         at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:412) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:476) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
>         at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:394) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
>         at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:153) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
>         at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
>         at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
> Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R3.Block
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:91) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
>         at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_91]
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_91]
>         ... 14 more

Im using CraftBukkit version git-Spigot-1.7.9-R0.2-207-g03373bb (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)

**Comment by RoboMWM** [comment]
If you're using 1.7.9, use a version for 1.7.9... see http://dev.bukkit.org/bukkit-plugins/orebfuscator/files/

**Comment by Bielecki** [comment]
Downloaded version 2.1.7 designed for "CB 1.7.9-R0.2CB 1.7.2-R0.3CB 1.6.4-R2.0". Getting error and plugin doesn't even load:

> [20:36:56] [Server thread/WARN]: Skipping loading of Orebfuscator as it does not work with Spigot 1.8 builds!

**Comment by RoboMWM** [comment]
Idk, try older versions, or you have some plugin that's able to screw around with orebfuscator's version checking (perhaps you're running a protocol-hacked version?)

**Comment by Bielecki** [comment]
If you mean this, it's version you can connect using both 1.7.x and 1.8.x client versions. Can I disable version checking in orebfuscator?

**Comment by Aleksey-Terzi** [comment]
If you are using server with 1.7.10-R0.1-SNAPSHOT API, then try please 2.1.6: http://dev.bukkit.org/bukkit-plugins/orebfuscator/files/137-orebfuscator-2-1-6/

**Comment by Bielecki** [comment]
Nope, sorry:

> [22:03:26] [Server thread/WARN]: Skipping loading of Orebfuscator as it does not work with Spigot 1.8 builds!

**Comment by RoboMWM** [comment]
> If you mean this, it's version you can connect using both 1.7.x and 1.8.x client versions. Can I disable version checking in orebfuscator? 

That's likely the cause, then. You could try forking the repo and reverting to an older commit and disable it from there.

**Comment by Aleksey-Terzi** [comment]
@Bielecki

As suggested RoboMWM - the best way for you to make fork of old Orebfuscator version and make required fixes.
We are not providing 'development' support for Orebfuscator targeted to Minecraft versions older than 1.9.
