### ISSUE TITLE
RandomBlocks not accepting CHEST

### ISSUE THREAD

**Issue by jaimelive** [lishid/Orebfuscator#117]
When in engine mode 2, CHEST in the RandomBlocks list is ignored, I cannot seem to find any documentation on this issue, sorry if I missed the point.

**Comment by Aleksey-Terzi** [comment]
Tile entities (signs, chests and etc) cannot be used in RandomBlocks list, therefore there are no way to add chest to RandomBlocks.

I've updated wiki with this info. Thanks for declaring about problem.
