### ISSUE TITLE
Not working on Thermos

### ISSUE THREAD

**Issue by WinSide** [lishid/Orebfuscator#118]
http://pastebin.com/LtgMdT1r
More logs paste to pastebin

**Comment by Aleksey-Terzi** [comment]
Sorry but we are not providing 'development' support for Orebfuscator targeted to Minecraft older than 1.9 version.
I propose to make fork of old version of Orebfuscator and try to fix issue by yourself.

**Comment by WinSide** [comment]
I dont know how to fix

**Comment by LiamtjuhhZ** [comment]
yeah, it seems not to work...
