### ISSUE TITLE
Viaversion server

### ISSUE THREAD

**Issue by TerZer** [lishid/Orebfuscator#120]
Hi, I have 1.8.8 minecraft server who has viaversion, that people can join on 1.9 and 1.10. So I have problem, I can't use 1.9 or 1.10 releases, but when I use 1.8 plugin, it will load, but when 1.9 or 1.10 player join to server it will make a lot of errors. So what I need to do?

**Comment by RoboMWM** [comment]
That's the risk you run with viaversion, or any other protocol-altering plugin. Since this plugin sends the obfuscated chunks to the client, it's only going to send the chunk appropriate for the version it is on.

**Comment by TerZer** [comment]
Hmmm.. Okey, will try that, but if you could make 1.8 - 1.10 support, I would be really happy :+1:

**Comment by RoboMWM** [comment]
And that'd be a nightmare to support and maintain I'd bet

**Comment by TerZer** [comment]
Ok, but mayby then you can fix this:
http://pastebin.com/rQHdW1Ai

It only shows then I open xray ONLY on huzuni 1.8 version. If only you could fix that...

**Comment by TerZer** [comment]
And there's a big bug, that then player use chests, console get flood by warnings, but that's not effect world.

**Comment by TerZer** [comment]
But I really want to make clear console and your plugin is best <3 So I don't know what to do. Btw spigot anti xray is shitty. :(

**Comment by RoboMWM** [comment]
spigot antixray uses this same codebase.

(ok not exactly the same code but they did get this guy to help develop the spigot antixray, so a lot of the code is similar).

**Comment by TerZer** [comment]
Spigot anti xray is bad because it can't hide blocks like orebfuscator does. Orebfuscator also removes ChestESP and Huzuni x-ray, that spigot anti x-ray can't..

**Comment by RoboMWM** [comment]
> it can't hide blocks like orebfuscator does

It's (nearly) the exact same engine.

**Comment by TerZer** [comment]
It can't hide chest from ChestESP and huzuni can bypass it. So that's why I using orebfuscator.

**Comment by Aleksey-Terzi** [comment]
Sorry but we are not supporting "coding support" of Orebfuscator for versions older than 1.9.
If it is not working in 1,8.x as you expecting - then I would suggest to make Orebfuscator's fork and try to fix it by yourself.
