### ISSUE TITLE
Anti-Xray Lag

### ISSUE THREAD

**Issue by SpacePuppeh** [lishid/Orebfuscator#123]
One of my players is claiming that there's lag while using 3D textures with my server. I have redstone blocks and TNT added to the obfuscated blocks to explode worlds of world downloaders (lol) so what do you think about this?

See here for the video sent from the player trying to walk around in the world with the texture pack on: https://drive.google.com/open?id=0B9zn-T_nRfz-Y2xsLXFfa1U4djg

Note that this only happens when he is using this texture pack with 3d, not super HD textures, not normal textures, only 3D ones.

Is it possible that the 3D textures need to render adjacent blocks – more blocks than normally rendered for default, non-3D textures?

**Comment by RoboMWM** [comment]
Sounds like a client issue. If so, nothing we can do server-side other than use blocks that the client won't lag with or w/e

**Comment by Aleksey-Terzi** [comment]
@SpacePuppeh

I'm agree with RoboMWM, looks like this is client-side issue.
I have the same effect with X-Ray mod when Orebfuscator's EngineMode = 2, because of it tries to render too much different blocks.

Try to set EngineMode = 1 and look if this solve the problem.

**Comment by SpacePuppeh** [comment]
I agree, it looks client side, but if there's a way to tweak the plugin so to not lag people with this setup it'd be nice, but it looks not possible from what I hear.

**Comment by RoboMWM** [comment]
> if there's a way to tweak the plugin so to not lag people

Engine mode 1

**Comment by SpacePuppeh** [comment]
Right right I understand that, but I meant using my current configuration, since I like engine 2 better for my server since mining is a huge part of it. Since there's not it's not a big deal, just using that specific kind of texture might create lag.
