### ISSUE TITLE
"Player tried to hack with packet spamming."

### ISSUE THREAD

**Issue by Blackyvk** [lishid/Orebfuscator#126]
Today my players said they were lagging, i check the log and found for about 3 minutes that message

"Player tried to hack with packet spamming."

any idea why and how to prevent this from happening again ? thanks.

**Comment by Aleksey-Terzi** [comment]
Are you sure this error message is related to Orebfuscator?
Could you please provide part of log file with this message? (full log file would be much better)

**Comment by Blackyvk** [comment]
that message [ it's in the code ](https://github.com/lishid/Orebfuscator/blob/07342b5e10e5d61b6e741cdc441ab6ed4f60c3d9/Plugin/src/main/java/com/lishid/orebfuscator/hithack/PlayerBlockTracking.java)

the log  just shows a spam of that message for over 2 minutes, nothing else is really relevant.

**Comment by Aleksey-Terzi** [comment]
Without log I can't tell nothing

**Comment by ProgrammerDan** [comment]
If its in the code, I'd suggest that perhaps Orebfuscator is working as designed. Investigate the player whose name is in the log, perhaps watch them in GM3, and see if they are behaving badly.

**Comment by Aleksey-Terzi** [comment]
I;m supposing plugin is working as expected and therefore closing issue.

**Comment by RoyCurtis** [comment]
Really sorry to comment on an old issue like this, but I've just hit this problem today (and this is the only hit on Google...)

Is it possible to turn off this feature? As far as I can tell, there is nothing relevant in the config for this.
