### ISSUE TITLE
I used Orebfuscator a few years ago, how does it perform now?

### ISSUE THREAD

**Issue by Wabbitface** [lishid/Orebfuscator#127]
I was quite happy using Orbfuscator until it was causing a lot of problems for those players who play the game normally. They would find random ores flash before their eyes while mining then returning to their original block. 

I was wondering if this is still a problem in this current version of Orefuscator, or whether or not it was a server performance issue and that if the server is under heavy load it would mean Orebfuscator wouldn't work as well.

Any answers are much appreciated .

**Comment by ProgrammerDan** [comment]
Random Ores is a configurable engine mode -- Orebfuscator supports two modes, one that replaces "unexposed" blocks with random ores (that would lead to the reports your players shared) and another mode that replaces "unexposed" blocks with just stone (or the block of your choice).

Performance wise we've had very few complaints about this "Orebfuscator 4" version; I'd recommend strongly giving it a try, and use Engine Mode 1 to avoid the random ores complaints.

Information on configuring:

https://github.com/lishid/Orebfuscator/wiki/How-to-properly-configure-Orebfuscator

https://github.com/lishid/Orebfuscator/wiki/Configuration-File

If you run into any trouble at all, drop us an issue here. Aleksey especially is very quick to respond, as are others who also use Orebfuscator regularly.

**Comment by Wabbitface** [comment]
I share my thanks, I will be testing this out.

**Comment by RoboMWM** [comment]
Also ensure `update-radius` isn't set to greater than 3

**Comment by Wabbitface** [comment]
Thanks, currently I had to configure the plugin so players weren't penalised with weird glitches like their furnaces, workbenches, dispensers, chests and enchantment tables were just stone blocks.

This is the sort of thing that discouraged me from using this plugin in the first place, but at least I can configure it to my needs.

**Comment by ProgrammerDan** [comment]
These things you describe as "glitches" are named and expected features :).

Certain types of things aren't "normal blocks" but are Block or Tile Entities -- They are "alive" -- orebfuscator handles them special using what is called Proximity Hider, so that "x-rayers" can't see these special blocks (especially chests) from across the map and tunnel straight to them.

In any case, absolutely glad to hear you're finding it easy to configure.

With regards to your glitch, change to Engine Mode 1.

**Comment by Wabbitface** [comment]
"It's not a bug, it's a feature!" hehe
Changed to Engine mode 1, I see why you still have engine mode 2 because now with engine 1, xrayers can easily see mine shafts and dungeons. Any workaround solutions to this?

**Comment by ProgrammerDan** [comment]
A few options exists; you could use engine mode 2 but a more "normal" blend of blocks in the configuration -- stone, cobblestone, mossy cobble, dirt, gravel, wood planks, logs, perhaps a single ore type -- and use 2 as your update radius, 3 if you've got a beefier CPU behind your server and players usually mine with Eff 5 equipment. 

The update radius controls how many blocks "around" the broken block get de-obfuscated, so a big number is a huge performance drain, but with faster tools sometimes they will block breaks more quickly then deobfuscation can keep up with, leading to the "glitches" you reported before. It's a bit of a balancing act.

Another option is to turn _back on_ Proximity Hider; add Mossy Cobble, chests, spawners to the list. This will at least disguise dungeons a bit better; mineshafts are more difficult to hide and honestly only Engine Mode 2 with a good blend of "target" materials for X-rayers will be effective.

Hope this helps a bit!

**Comment by RoboMWM** [comment]
> Changed to Engine mode 1, I see why you still have engine mode 2 because now with engine 1, xrayers can easily see mine shafts and dungeons. Any workaround solutions to this?

Xrayers can easily see these regardless of the engine mode. The "antifreecamandtexturepack" option makes this a bit harder to do, but structures are generally pretty easy to make out, simply because they consist of air

**Comment by ProgrammerDan** [comment]
The only difference is engine mode 1 obfuscates exclusively to stuff that most x-ray packs display as transparent, whereas in default configuration engine mode 2 obfuscates to stuff that x-ray packs/mods either leave opaque or only partially make transparent, thus while you are completely correct @RoboMWM arguably engine mode 2 at least makes them work a little harder :)

**Comment by Wabbitface** [comment]
Exactly what I was thinking. Okay what I will try to do is configure with engine mode 2 so there is a mixture of natural blocks you would expect to see underground. That being  Air, Stone, andesite, gravel, dirt, coarse dirt, granite and Diorite. 

Thoughts?

My machine is actually got plenty of cpu recourses available (using 25% at the most) however I like to keep things running as efficient as possible without disrupting normal players mining ingame.

The other thing I needed to tweak was chests, furnaces, dispensers, workbenches and enchantment tables as they were also included in the list of blocks to be obfuscated. Which in my opinion is a bit silly because it's really obnoxious seeing them as stone blocks in players own bases above ground.

**Comment by ProgrammerDan** [comment]
I haven't used it much myself but I believe ProximityHider has a Y cap limit you could use; so if you feel comfortable, you could configure ProximityHider to only "hide" chests and such below sea level.

The config parameter:

`ProximityHiderEnd`

Read more here: https://github.com/lishid/Orebfuscator/wiki/Configuration-File

**Comment by Wabbitface** [comment]
set UseYLocationProximity: true ?

**Comment by ProgrammerDan** [comment]
Good catch; yes, that needs to be set as @Wabbitface indicated.

**Comment by Aleksey-Terzi** [comment]
I'm guessing issue could be closed.
If more questions - please reopen.
