### ISSUE TITLE
EntityChangeBlockEvent not causing block updates

### ISSUE THREAD

**Issue by Jikoo** [lishid/Orebfuscator#128]
Largely an issue related to silverfish - players mining in Extreme Hills oftentimes expose fake ores and complain.
![2016-09-01_15 58 15](https://cloud.githubusercontent.com/assets/1353270/18183173/235c28bc-7061-11e6-9fca-d733bed65e14.png)
This can be fixed with a small addition to OrebfuscatorEntityListener:
``` Java
    @EventHandler(priority = EventPriority.MONITOR, ignoreCancelled = true)
    onEntityChangeBlock(EntityChangeBlockEvent event) {
        BlockUpdate.update(event.getBlock());
    }
```
I'd submit a PR, but quite honestly, I'd just do it via Github web because I'm too lazy to clone the repo for such a tiny change.

**Comment by Aleksey-Terzi** [comment]
Thanks for declaring about the problem and suggesting solution.

**Comment by Aleksey-Terzi** [comment]
Requested changes is in latest release.
