### ISSUE TITLE
Disable specific worlds, 4.2.0 with spigot 1.11

### ISSUE THREAD

**Issue by Fabii777** [lishid/Orebfuscator#136]
Hello,
i want to disable some worlds and tryed the old configuration the the new one, but i think i do something wrong with the new one, first i tryed to add UseWorldsAsBlacklist: default:true & worlds: testworld to my conf, but this didnt work ---> reset Config

And the second try was to add this 

  Noone:
    Names:
    - testworld
    Mode1Block: STONE
    RandomBlocks:
    ObfuscateBlocks:

But this didnt work too^^

How its possible to disable worlds ?

**Comment by RoboMWM** [comment]
Paste your config here: https://gist.github.com/ and paste the link here.

Adding sections into any config will do nothing unless you know the exact section the code is looking for. So don't do that.

**Comment by Fabii777** [comment]
Why should i paste the standart config without any modifications ? I just describe what i tested and asked how to disable or what i have to add to disable a spcific world.

**Comment by Fabii777** [comment]
Now i modifed a config for u to show what i tested ....


https://gist.github.com/Fabii777/ce04106373e422d05e9dd7eb396e38e8

**Comment by RoboMWM** [comment]
Ok yea you can't just make up your own config sections, also I don't think null config sections means it won't do anything.

I'd look at the TYPES but then again I'm not 100% sure. Did you check the wiki?

**Comment by Fabii777** [comment]
Sure it not works!! I wrote it was a test and it didnt work.... and i ask how to disable specific worlds....
And Sure i checked the wiki, thats why i write here... 
I just wanna know how i to disable specific worlds and not a comment that things not work although i said that this test do not work..
If u dont know it, just say it and not comment any spamm..

**Comment by ProgrammerDan** [comment]
https://github.com/lishid/Orebfuscator/wiki/Configuration-File-(4.1.14)

Please direct your attention to the PerWorld configuration section, and note that simply adding 
`Enabled: false` will disable that specific world, as described in the configuration help...

**Comment by Aleksey-Terzi** [comment]
Just renamed page to https://github.com/lishid/Orebfuscator/wiki/Configuration-File

**Comment by Dreadonator** [comment]
I have the same issues aswell! and people on spigot also dont undertand it! can you provide us a full example config please? that would be grate!

**Comment by RoboMWM** [comment]
@Dreadonator the examples are on the bottom. Simply set the `Enabled` key to false (as indicated in the second example)
