### ISSUE TITLE
Add an example configuration to wiki

### ISSUE THREAD

**Issue by RoboMWM** [lishid/Orebfuscator#137]
So, it seems a lot of people are confused on how to do things like disable a world from being obfuscated. I took a look at the wiki, and although I could spend time and guess/experiment with different settings myself, it'd probably be best to add an example one to it.

**Comment by ProgrammerDan** [comment]
Agreed, although the 4.1.14 update config is quite clear; but we should probably have better navigation and clarity, including example configs.

**Comment by Aleksey-Terzi** [comment]
Yes, you are right, thanks for suggestion.
New section have been added to "Configuration File" page: [Example: how to disable or enable worlds](/lishid/Orebfuscator/wiki/Configuration-File#example-how-to-disable-or-enable-worlds)
