### ISSUE TITLE
3.0.6R3 Bug

### ISSUE THREAD

**Issue by SnakeDaoust1232** [lishid/Orebfuscator#145]
Desc: Randomly, ill get a player on my server complaining that "my chests keep flasing!!!! HELPPPP". The only way to fix it is to disable the proximity hider and the only reason i use the plugin is for proximity hider, so basically i have to disable the entire plugin every time this happends. Im keeping the plugin disabled until this issue is resolved.

I've tried disabling the update and initial radius. All combinations.

*Every item that i have in the proximity hider flashes/dissapears and reapears*

Video: https://www.youtube.com/watch?v=FMSuxDF_s-M&feature=youtu.be
Version: 3.0.6 R3
Config: https://hastebin.com/naqebamiho.scala
PaperSpigot 1.8.8
ProtocolLib version 4.2.0 (Latest)
ProtocolSupport to allow 1.7 client to join a 1.8 server.

**Comment by Aleksey-Terzi** [comment]
Sorry but we are not providing support for Orebfuscator for Minecraft with version less than 1.9.

**Comment by SnakeDaoust1232** [comment]
That sucks cause now i have to stop using it.
