### ISSUE TITLE
i just can't get orebfuscator to work.

### ISSUE THREAD

**Issue by Dylan123111** [lishid/Orebfuscator#150]
i just can't get orebfuscator to work, it says that it isnt enabled in any world but i am sure i enabled it an restarted the server and reloged

**Comment by ProgrammerDan** [comment]
Can you please share you config and perhaps the server log where it isn't enabling? Thanks!

**Comment by Dylan123111** [comment]
ConfigVersion: 13
Booleans:
  UseCache: true
  Enabled: true
  UpdateOnDamage: true
  NoObfuscationForMetadata: true
  NoObfuscationForOps: false
  NoObfuscationForPermission: false
  LoginNotification: true
Integers:
  MaxLoadedCacheFiles: 64
  DeleteCacheFilesAfterDays: 0
  EngineMode: 2
  InitialRadius: 5
  UpdateRadius: 4
Strings:
  CacheLocation: orebfuscator_cache
  NoObfuscationForMetadataTagName: NPC
Lists:
  TransparentBlocks: []
  NonTransparentBlocks: []
Worlds:
  Default:
    Types:
    - DEFAULT
    Enabled: true
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: true
    DarknessBlocks:
    - MOB_SPAWNER
    - CHEST
    Mode1Block: STONE
    RandomBlocks: []
    ObfuscateBlocks: []
    ProximityHider:
      Enabled: true
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - DISPENSER
      - MOB_SPAWNER
      - CHEST
      - DIAMOND_ORE
      - WORKBENCH
      - FURNACE
      - BURNING_FURNACE
      - ENCHANTMENT_TABLE
      - EMERALD_ORE
      - ENDER_CHEST
      - ANVIL
      - TRAPPED_CHEST
  Normal:
    Types:
    - NORMAL
    Mode1Block: STONE
    RandomBlocks:
    - STONE
    - COBBLESTONE
    - WOOD
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - TNT
    - MOSSY_COBBLESTONE
    - OBSIDIAN
    - DIAMOND_ORE
    - REDSTONE_ORE
    - CLAY
    - EMERALD_ORE
    ObfuscateBlocks:
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - CHEST
    - DIAMOND_ORE
    - REDSTONE_ORE
    - GLOWING_REDSTONE_ORE
    - EMERALD_ORE
    - ENDER_CHEST
  TheEnd:
    Types:
    - THE_END
    Mode1Block: ENDER_STONE
    RandomBlocks:
    - BEDROCK
    - OBSIDIAN
    - ENDER_STONE
    - PURPUR_BLOCK
    - END_BRICKS
    ObfuscateBlocks:
    - ENDER_STONE
  Nether:
    Types:
    - NETHER
    Mode1Block: NETHERRACK
    RandomBlocks:
    - GRAVEL
    - NETHERRACK
    - SOUL_SAND
    - NETHER_BRICK
    - QUARTZ_ORE
    ObfuscateBlocks:
    - NETHERRACK
    - QUARTZ_ORE

**Comment by ProgrammerDan** [comment]
Do you have protocollib installed?

Please use pastebin or similar to share logs / configs for better readability.

**Comment by Dylan123111** [comment]
sorry for waiting so long, but i finally copied it so i hope you can help me now
https://pastebin.com/Yh5vfjfs

**Comment by Dylan123111** [comment]
perhaps my configuration is outdated.

**Comment by ProgrammerDan** [comment]
I did see some folks indicate they had to delete and allow their configuration to automatically regenerate to bypass some errors on updating to latest. You might try that first.

Otherwise, it's likely a dependency problem, for instance if you lack ProtocolLib or your version of Protocollib is too old. 

Can you share via pastebin your startup log showing the error / failure in Orebfuscator (if any)?

**Comment by Dylan123111** [comment]
I deleted my configuration and started the server and typed in /ofc engine 2

**Comment by Dylan123111** [comment]
I deleted my configuration and started the server and typed in /ofc engine 2
/ofc enable . but the last time i did /ofc status i read worlds: none

**Comment by Dylan123111** [comment]
btw i didn't find any errors in the logs

**Comment by Dylan123111** [comment]
nope it didn't work

**Comment by Dylan123111** [comment]
this is a screen of what i see when i do /ofc status
https://1drv.ms/u/s!AnLNKD9XpUillTvz-CJNl2OeafOA

**Comment by Dylan123111** [comment]
srry i thought that that was some kind of thing like pastebin to make it easier to read certain things but thanks

**Comment by Dylan123111** [comment]
thanks it worked

**Comment by ProgrammerDan** [comment]
Great! Glad to hear :). Please let us know if you run into other problems, be sure to read over the wiki (here: https://github.com/lishid/Orebfuscator/wiki) for configuration tips.
