### ISSUE TITLE
Needs update to 1.12

### ISSUE THREAD

**Issue by Fonzee9** [lishid/Orebfuscator#154]
https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-12-pre2-released.240317/

**Comment by Fonzee9** [comment]
I really need this plugin on my server :) Please update it for 1.12 as its not working

**Comment by RoboMWM** [comment]
Patience, I'm sure they're aware as they own a server too.

**Comment by ProgrammerDan** [comment]
Yeah, give it a bit. @Aleksey-Terzi is aware of the update I'm sure, once he gets it working I'll make appropriate release packaging for everyone :).

**Comment by Aleksey-Terzi** [comment]
Support for 1.12-pre2 is added.
Changes pushed to DevotedMC fork.

ProtocolLib should be updated to the latest version to work properly.

**Comment by ProgrammerDan** [comment]
I'll upload a build a little later.

**Comment by Fonzee9** [comment]
Okay thank you so much 👍

**Comment by ProgrammerDan** [comment]
@Fonzee9 https://github.com/lishid/Orebfuscator/releases/tag/4.3.0

Please note this is for 1.12-pre2 -- build spigot against --dev  for compatible version. Be absolutely sure to use latest DEV Protocollib.

Good luck, let us know if you run into issues.
