### ISSUE TITLE
Forge (Bukkit & forge)

### ISSUE THREAD

**Issue by LiamtjuhhZ** [lishid/Orebfuscator#158]
Hi, im using forge and bukkit for 1.7.10, I have orebfuscator and protocollib installed, but when I try to use x-ray, it doesnt block the xray at all, even not the vanilla ores, and not the modded ones..
it didnt even work before I changed the config
config file:

ConfigVersion: 10
Integers:
  EngineMode: 2
  InitialRadius: 1
  UpdateRadius: 2
  ProcessingThreads: 3
  MaxLoadedCacheFiles: 64
  ProximityHiderDistance: 8
  ProximityHiderID: 1
  ProximityHiderEnd: 255
  AirGeneratorMaxChance: 43
  OrebfuscatorPriority: 1
  CompressionLevel: 1
Booleans:
  UseProximityHider: true
  UseSpecialBlockForProximityHider: true
  UseYLocationProximity: false
  UpdateOnDamage: true
  DarknessHideBlocks: false
  NoObfuscationForOps: false
  NoObfuscationForPermission: false
  UseCache: true
  LoginNotification: true
  AntiTexturePackAndFreecam: true
  Enabled: true
  CheckForUpdates: true
Lists:
  ObfuscateBlocks:
  - 1089:6
  - 129
  - 153
  - 73
  - 21
  - 16
  - 15
  - 56
  - 14
  - 167
  - 466
  - 468
  - 468:2
  - 468:4
  - 468:6
  - 468:8
  - 468:10
  - 468:12
  - 468:14
  - 610
  - 611
  - 612
  - 613
  - 697
  - 697:1
  - 697:2
  - 697:3
  - 697:4 
  - 697:5
  - 697:7
  - 697:8
  - 697:10
  - 697:9
  - 697:11
  - 925
  - 698
  - 959:4
  - 959:5
  - 958:1
  - 1584:7
  - 958:3
  - 958:4
  - 958:5
  - 959
  - 959:1
  - 959:2
  - 959:3
  - 1345
  - 1560
  - 1089:7
  - 1134
  - 1122:5
  - 958:2
  - 1584:4
  - 1584:6
  - 1584:11
  - 1584:5
  - 1584:12
  - 1584:13
  - 1584:15
  - 1584:9
  - 1584:10
  - 1584:3
  - 1584:2
  - 1584:1
  - 1584
  - 1584:14
  - 1584:8
  - 1104:1
  - 1122:4
  - 1104:2
  - 1089:8
  - 1122?3
  - 166
  - 1104
  - 1134:1
  - 1089:5
  NetherObfuscateBlocks:
  - 87
  - 153
  DarknessBlocks:
  - 52
  - 54
  ProximityHiderBlocks:
  - 23
  - 52
  - 54
  - 56
  - 58
  - 61
  - 62
  - 116
  - 129
  - 130
  - 145
  - 146
  DisabledWorlds: []
  RandomBlocks:
  - 1
  - 4
  - 5
  - 14
  - 15
  - 16
  - 21
  - 46
  - 48
  - 49
  - 56
  - 73
  - 82
  - 129
  NetherRandomBlocks:
  - 13
  - 87
  - 88
  - 112
  - 153
Strings:
  CacheLocation: orebfuscator_cache

**Comment by LiamtjuhhZ** [comment]
I am using thermos for 1.7.10, and yes, I have seen your old issue, but please help.

**Comment by RoboMWM** [comment]
You can ask all you want, but the answer isn't going to change. Perhaps hire a developer to fix the 1.7.10 version?

**Comment by LiamtjuhhZ** [comment]
How? Where? I mean like im not the only one who is having this problem but I cant find anyone else...

**Comment by RoboMWM** [comment]
> Where?

One such place: https://www.spigotmc.org/forums/services-recruitment-v2.54/

**Comment by ProgrammerDan** [comment]
Unfortunately we just aren't in a position to support or develop for very old minecraft releases. Your specific case is even further outside our norm, as its dealing with frameworks outside the initial target (bukkit & forge via thermos -- which should probably work but I don't believe was ever officially supported, could be wrong).

So, sorry you're having these issues; might check on some development forums for coders still working with that revision of Bukkit / Forge and see if they might be willing to work on it for you. The code is still here, and latest "pre-1.8" release last commit is here: 

https://github.com/lishid/Orebfuscator/tree/510222c0e49e43b924e37d2018727ec452e901b5

which includes support for 1.7.x and prior, although without any modern improvements so no idea how it will perform.

Good luck!

**Comment by LiamtjuhhZ** [comment]
Okay, well thanks for your help
