### ISSUE TITLE
Orebfuscator Preformance needs improvement drops tps from 20 to 11

### ISSUE THREAD

**Issue by Fonzee9** [lishid/Orebfuscator#162]
Somethings that need improvement from the tps monitor from 20 to 11

![2017-06-23_22 22 04](https://user-images.githubusercontent.com/21323258/27504956-7031a862-5862-11e7-85a7-c110835e8aaa.png)
![2017-06-23_22 14 14](https://user-images.githubusercontent.com/21323258/27504935-2d73ee9a-5862-11e7-9631-95d485458347.png)
![2017-06-23_22 14 15](https://user-images.githubusercontent.com/21323258/27504936-2ee9360e-5862-11e7-8d07-77d60e0846e0.png)
![2017-06-23_22 14 17](https://user-images.githubusercontent.com/21323258/27504938-303bf118-5862-11e7-9cd3-a0c1e959c175.png)

**Comment by RoboMWM** [comment]
Including a `/timings paste` as well as your config might be helpful, since we have no idea how to interpret the data from this "spike monitoring" plugin (e.g. no context nor data labels)

**Comment by Fonzee9** [comment]
I was told i could use that timings to show lag spikes... guess not

**Comment by ProgrammerDan** [comment]
You can use it -- we just need a bit more information to make sense of it. 

Do you have that same data, extracted from the server logs? That might help a lot.

**Comment by RoboMWM** [comment]
Well the config can help determine what blocks and engine mode you're using (and whether you're using the cache and not), and the timings can help us see what else is going on (chunks being generated, lots of players moving around/mining?)

The plugin is _ok_ to use, but for finding out exactly what's causing the lag, more information helps us better understand how the lag is coming about.

**Comment by Fonzee9** [comment]
Using default config

**Comment by Fonzee9** [comment]
https://pastebin.com/K3nYtwFH

**Comment by ProgrammerDan** [comment]
Any thoughts @Aleksey-Terzi ?

**Comment by Aleksey-Terzi** [comment]
@ProgrammerDan thanks

@Fonzee9 could you please provide more details of how to reproduce problem?
For example these are my timings on test server with 1 player: https://timings.spigotmc.org/?url=futukaregi
Maybe problem somehow related to memory issues?
Do you have any statistics about memory usage?
Also try to disable cache, i.e. set Booleans.UseCache = false

**Comment by Fonzee9** [comment]
@Aleksey-Terzi your misunderstanding what the plugin does it detects spikes Spigot's timings doesn't thats why its unseeable in your timings.

**Comment by RoboMWM** [comment]
@Fonzee9, paper's timings definitely shows spikes, and spigot's timings do indicate which plugins and what methods have been causing spikes overall.

**Comment by Aleksey-Terzi** [comment]
@Fonzee9 I'm just trying to tell you that I don't see problem and therefore I cannot fix it.
I would appreciate if you could provide step by step description of what I should do to see the issue.
Also please try to disable cache.
