### ISSUE TITLE
INFO Orebfuscator 4.2.1 is: ProtocolLib is not found! Plugin cannot be enabled.

### ISSUE THREAD

**Issue by Toninom** [lishid/Orebfuscator#163]
As I wrote on the title, i'm unable to activate the plugin. Of course protocollib is already installed. What to do?

**Comment by RoboMWM** [comment]
what version of protocollib? and server version?

**Comment by Toninom** [comment]
Server spigot 1.12, protocollib Version: 4.2.1

**Comment by RoboMWM** [comment]
your protocollib and orebfuscator are both outdated

**Comment by ProgrammerDan** [comment]
As RoboMWM correctly commented, you must use ProtocolLib 4.3.0 latest release for compatibility with Orebfuscator -- which you should also update to 4.3.0(2) for 1.12 support, as the version you list in the title has _no_ compatibility for 1.12 (it only supports up to 1.11).
