### ISSUE TITLE
Your release-download server is detected as a "Deceptive site" for Chrome

### ISSUE THREAD

**Issue by j-lorenzo** [lishid/Orebfuscator#165]
![image](https://user-images.githubusercontent.com/16794234/28570570-03f26402-713f-11e7-9a87-f404c0be5fc5.png)

**Comment by Aleksey-Terzi** [comment]
I'm supposing this is not Orebfuscator's issue, but issue between Chrome and github?

**Comment by ProgrammerDan** [comment]
Yeah, sounds like Github and Chrome in your region are having a little spat. Nothing we can do. I upload the releases to Github; I don't control where they are hosted or what issues that host might have.
