### ISSUE TITLE
Securely problem. very Important!!!  Orebfuscator4 versus  EntityLWC

### ISSUE THREAD

**Issue by Kuroyabumozu** [lishid/Orebfuscator#166]
Hello, I got a bug, that is when your server has installed Orebfuscator4, 
when you are get lagging or very lagging and see the chest is hide by stone, you will be able to open a private LWCchest created by other player without share permissions.

**Comment by ProgrammerDan** [comment]
Can you explain a bit more? I'm not clear how this would be an Orebfuscator issue. 

What do you mean by laggy? The server (TPS) is poor (less then 18.0?) or the clientside is poor (frames per second is low)?

Is EntityLWC sending its own chest / tile entity update packets? 

If this "laggy" environment exists apart from Orebfuscator, can you do the same thing (open a private LWCchest created by "other player" without share permissions)?

**Comment by Kuroyabumozu** [comment]
Yes, I can explain more, I'm not sure if it is not EntityLWC problem, but I already submit this issue to them, and here's what they replied to me.
![image](https://user-images.githubusercontent.com/20812714/28633717-c5f012c0-7202-11e7-8366-c39137643134.png)

I think both (TPS, FPS) has this problem, 
because however Server doesn't give too much internet flow to each player,
it will cause that player lag and did not process something out fast that will makes player laggy and player will able to open LWC private chest before LWCchest has not been complete load with Orebfuscator. or clientside is poor will cause this problem too, because clientside can't get fast connect on this process that is like laggy and then they are able to bug~

and I haven't test for another way for if I don't have Orebfuscator will it cause this problem happens.

**Comment by ProgrammerDan** [comment]
Most other authors will just tell you to complain to us. So far, it's almost never us.

We don't modify blocks! We don't modify chests! We just manipulate what the client sees, literally _only_ packet manipulation. Nothing else.

90% likely this issue exists without Orebfuscator. Something with LWC is allowing this edge case to emerge, and it likely exists without Orebfuscator.

**Comment by Kuroyabumozu** [comment]
what... I don't understand how is this problem will exists without Orebfuscator ?
it is obviously because of the Orebfuscator have within.....

**Comment by ProgrammerDan** [comment]
I don't understand your sentence structure there.

What I'm trying to say is that, Orebfuscator doesn't actually change anything. So if there's a way to bypass LWC's protections, it exists without Orebfuscator, as orebfuscator doesn't actually change anything in the blocks or block data or tile entity data.

**Comment by Kuroyabumozu** [comment]
all right.. I got you

**Comment by GershonR** [comment]
I'm having this exact problem with Orebfuscator, EntityLWC said it's a Orebfuscator problem 
https://github.com/Tsuser1/Modern-LWC/issues/73

**Comment by ProgrammerDan** [comment]
Yes, that is what they claim, they are incorrect. We discovered the issue that EntityLWC has, in our other plugin Citadel -- it is independent of Orebfuscator, and deals with a bypass mode for handedness, their protection routine is improperly coded.

Orebfuscator _does_ make it easier to generate the client-side packetstate that causes the bypass, but it is easily created using a packet-shaping client-side mode, and I'd suspect most hacked clients have it baked in. We've confirmed this on servers both with and without orebfuscator.

**Comment by ProgrammerDan** [comment]
@GershonR I've put some tips on the issue report on Modern-LWC -- I am not very intimate with that project but gave them what we'd found in Citadel. Hope it helps. If they aren't keen on doing the testing, I'd be happy to alter the line I identified and make a build for you to test with, if it might help.

Basically, if I'm right, everyone using Modern-LWC is vulnerable to hacked clients...
