### ISSUE TITLE
ProtocolLib is not found!

### ISSUE THREAD

**Issue by coolluck321** [lishid/Orebfuscator#168]
When i check the status ingame it tells me ProtocolLib is not found and that it could not be enabled. I have no clue what this is and how to fix it.

**Comment by ProgrammerDan** [comment]
Please read the _entire_ description and installation instructions here: https://www.spigotmc.org/resources/orebfuscator.22818/ -- instructions and link to ProtocolLib are there

**Comment by coolluck321** [comment]
Thank you so much. I am very sorry about that.

**Comment by ProgrammerDan** [comment]
Not a problem at all! Good luck, and let me know if you run into other troubles.
