### ISSUE TITLE
Performance drop on client side with orebfuscator on.

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [lishid/Orebfuscator#172]
System Windows 10 x64 10.0.16299.64
Geforce Driver 387.92
Minecraft 1.12.2
Server Spigot 1.12.2
```This server is running CraftBukkit version git-Spigot-00128b5-d063cd0 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)```

I own a server, I got a Nvidia installed on my gaming PC.
Betterfps and optifine mod.
With these, I can get 65 fps with 3120*2160 resolution, view distance set to 10.

When orebfuscator turned on, the fps drop to 47fps. 
After 40+ times "ofc reload", 5 hours adjust and test every settings I'm pretty sure this isn't because vertical sync or graphics driver.
I tried turn anything underground to air block, the fps still around 47.
(I find another github issue says more air block can caused worse performance)
The fps drop only happen when I'm look to the horizon whatever if I stand on my roof(y=85) or on bedrocks(y=3), when I look up the air or look down to my foot, fps returned to 65 fps.
Otherwise, if I lower view distance to 6, I can retrieve 65 fps, too. The other video settings seems completely no affect.
No matter the orebfuscator engine mode is 1 or 2, no different for client side performance drop.
If I just simple remove orebfuscator jar from plugins, no performance drop anymore.

Many low-end device gamer blame me that destroyed their game experience with less than 10 fps, before orebfuscator kicks in they can get 40+ fps.
The funny thing is though the server almost used double more memory than before, TPS keeps 19.9+ and I still have lots of memory are able to waste so on the server side there isn't any issue at all.

Could anyone give me some tweak suggests, please?
The following comments include plugin config.

**Comment by mhtvsSFrpHdE** [comment]
```ConfigVersion: 13
Booleans:
  UseCache: true
  Enabled: true
  UpdateOnDamage: true
  NoObfuscationForMetadata: true
  NoObfuscationForOps: false
  NoObfuscationForPermission: false
  LoginNotification: true
Integers:
  MaxLoadedCacheFiles: 64
  DeleteCacheFilesAfterDays: 0
  EngineMode: 2
  InitialRadius: 1
  UpdateRadius: 2
Strings:
  CacheLocation: orebfuscator_cache
  NoObfuscationForMetadataTagName: NPC
Lists:
  TransparentBlocks: []
  NonTransparentBlocks: []
Worlds:
  Default:
    Types:
    - DEFAULT
    Enabled: true
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    BypassObfuscationForSignsWithText: false
    DarknessBlocks:
    - MOB_SPAWNER
    - CHEST
    Mode1Block: AIR
    RandomBlocks: []
    ObfuscateBlocks: []
    ProximityHider:
      Enabled: true
      Distance: 16
      SpecialBlock: STONE
      Y: 62
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - DISPENSER
      - MOB_SPAWNER
      - CHEST
      - DIAMOND_ORE
      - WORKBENCH
      - FURNACE
      - BURNING_FURNACE
      - ENCHANTMENT_TABLE
      - EMERALD_ORE
      - ENDER_CHEST
      - ANVIL
      - TRAPPED_CHEST
      UseFastGazeCheck: true
  Normal:
    Types:
    - NORMAL
    Mode1Block: AIR
    RandomBlocks:
    - AIR
    ObfuscateBlocks:
    - STONE
    - DIRT
    - MOSSY_COBBLESTONE
    - BEDROCK
    - STATIONARY_LAVA
    - LAVA
    - STATIONARY_WATER
    - WATER
    - GOLD_ORE
    - IRON_ORE
    - COAL_ORE
    - LAPIS_ORE
    - CHEST
    - DIAMOND_ORE
    - REDSTONE_ORE
    - GLOWING_REDSTONE_ORE
    - EMERALD_ORE
    - ENDER_CHEST
    ProximityHider:
      Enabled: false
      Distance: 8
      SpecialBlock: AIR
      Y: 48
      UseSpecialBlock: false
      ObfuscateAboveY: false
      ProximityHiderBlocks: []
      UseFastGazeCheck: true
  TheEnd:
    Types:
    - THE_END
    Mode1Block: ENDER_STONE
    RandomBlocks:
    - BEDROCK
    - OBSIDIAN
    - ENDER_STONE
    - PURPUR_BLOCK
    - END_BRICKS
    ObfuscateBlocks:
    - ENDER_STONE
  Nether:
    Types:
    - NETHER
    Mode1Block: NETHERRACK
    RandomBlocks:
    - GRAVEL
    - NETHERRACK
    - SOUL_SAND
    - NETHER_BRICK
    - QUARTZ_ORE
    ObfuscateBlocks:
    - NETHERRACK
    - QUARTZ_ORE
```

**Comment by RoboMWM** [comment]
Mode 1 should provide the least FPS drops since it's only 1 block instead of a ton of different ores (and also easier to compress). I can't recall if I had issues client side with mode 2, but I have no complaints on mode 1 even with people with lower-end machines than I on my Intel HD graphics.

**Comment by mhtvsSFrpHdE** [comment]
@RoboMWM After a reload engine 1 with default stone make fps from 65 -> 57, adjust view distance from 10 to 9 can retrieve 65 fps. I'm still interested in the principles behind. Buildings on the ground are exactly the same as before, but game performance dropped just because things underground are changed.

Anyway in this situation the x-ray defense ability are... okay better than nothing.
Anti-cheat measures still hurt normal players and failed to stop cheaters.
It reminds me that I am doing something what I used to hate, fells like yet another StarForce.

So I decide to open "core protect" inspector and lookup command permissions to everyone, hopefully guys will know they can't escape from monitor.

And thank you, bring a very nice plugin to us after Spigot removed its feature.

**Comment by mhtvsSFrpHdE** [comment]
@RoboMWM Oh wait! It works! With engine 2 and turn off AntiTexturePackAndFreecam and then there isn't fps drop anymore! Seems the key is "generate air block". Thank you! This is aaaawesome

**Comment by mhtvsSFrpHdE** [comment]
@RoboMWM By the way I wish do a research about air block performance in Minecraft. Do you have any idea? Oh this is just my personal interest you can ignore this question HAHA.
