### ISSUE TITLE
2.1.7 corrupts after first use.

### ISSUE THREAD

**Issue by JonnyXX** [lishid/Orebfuscator#175]
I put in 1.2.7, start my server, works fine. Then, I close my server and start it again. "Invalid plugin.yml"

I try to pull it into Luyten, 

java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.zip.ZipFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at java.util.jar.JarFile.<init>(Unknown Source)
	at us.deathmarine.luyten.Model$6.run(Model.java:689)
	at java.lang.Thread.run(Unknown Source)

I don't want to have to re-download Orebfuscator every time I open my server.

**Comment by EvilOlaf** [comment]
Check your hard drive for corruption

**Comment by ProgrammerDan** [comment]
I'm sorry, but 2.1.7 is a phenomenally old and unsupported version. 1.2.7 is even older. I'm not sure which you are referring to, or what issue you are having. If you have an issue with 4.x.x series of Orebfuscator, I'd be happy to try to help, otherwise, I apologize but I am unable to help.

**Comment by JonnyXX** [comment]
1.2.7 was a typo, my bad. Does the newest Orebfuscator even work with 1.7.9 (don't tell me to update my server because it's not happening)?

**Comment by ProgrammerDan** [comment]
1.7.9 hasn't been supported by a main-line release in quite some time, I'm afraid. The last version that _might_ have supported it is 2.1.x -- which hasn't been supported in about 3 years. The current maintenance team (including myself) offers no support for any pre-4.x.x release of Orebfuscator, which offers support of MC 1.9 through 1.12. 

Your best bet is probably to try versions from here https://dev.bukkit.org/projects/orebfuscator/files?page=2 until you find one that works.
