### ISSUE TITLE
1.13 support?

### ISSUE THREAD

**Issue by Blockeri** [lishid/Orebfuscator#180]
[Spigot 1.13 dev build is available](https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-development-builds.328883/) and the latest ProtocolLib dev build already supports 1.13. Update for Orebfuscator would be highly appreciated.

**Comment by mirolm** [comment]
When it try the plugin on 1.13 the below error is visible in the server log:

`[18:57:40 ERROR]: Error occurred while enabling Orebfuscator4 v4.3.3 (Is it up to date?)
java.lang.NullPointerException: null
	at com.lishid.orebfuscator.Orebfuscator.loadOrebfuscatorConfig(Orebfuscator.java:104) ~[?:?]
	at com.lishid.orebfuscator.Orebfuscator.onEnable(Orebfuscator.java:71) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:424) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:338) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:214) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-ed1cec9-1c7adf7]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
`

**Comment by NullCase** [comment]
I am willing to give you my entire budget for ore block obfuscation to who ever releases a stable build first.

It looks like Paper 1.13 is working on their built in version now, but I wanted you to know so you don't lose the chance to get some money for producing this update.

What are your options for donating in support of this project @Aleksey-Terzi ?

**Comment by ProgrammerDan** [comment]
I haven't found Aleksey yet, hope he is OK. I have a long list of other plugins to also update, but hopefully will get this in the pipeline regardless if he appears or not. I cannot predict timing, though ... thanks for the offer of monetary support.

I guess this is an open call then -- if someone else feels comfortable issuing an approach-compliant update adding support for 1.13 in a non-breaking fashion, I'd be happy to review & merge, and perhaps NullCase might have a bounty for you (time depending).

**Comment by NullCase** [comment]
Just in case you're wondering, it looks like @stonar96 has made some excellent progress on a patch for paper. Still, it seems like there are some final steps ahead.

I don't know, it seems like there is no lead developer for orebfuscator.

What do you think @ProgrammerDan ?

**Comment by ProgrammerDan** [comment]
I still haven't heard from Aleksey, nor seen him online in any of his prior
hangouts. I hope to take a peak at upgrading Orebfuscator for 1.13
personally in the near future, although other personal obligations have
kept me from it to date. Still can't make any promise on ETA, but seeing no
interest from other parties, I'll give my "eventual best effort"
self-stamp; still glad to merge any credible, working PRs.

**Comment by jordanwilliams1** [comment]
Been waiting so long for this to update. It's vital to any survival server.

**Comment by jordanwilliams1** [comment]
@Aleksey-Terzi

**Comment by NullCase** [comment]
Paper 1.13 has produced a stable build and claimed the bounty.

**Comment by ProgrammerDan** [comment]
Sounds great! I am targeting end of September for 1.13 support for
Orebfuscator.

**Comment by molor** [comment]
Is there any way we can speed up the release of Orebfuscator for 1.13? Many people are only stopped by the lack of this plugin, and wait for another month - is unbearable for server administrators and players..

**Comment by ProgrammerDan** [comment]
I appreciate the difficulty in waiting, and if I can find time sooner I
will.

As stated previously, I'm also more then happy to review and merge credible
contributions of 1.13 upgrades; if someone maintaining a fork, for
instance, has put in the work already, I'm happy to merge it upstream.

Thanks for your continued patience, with respect to the difficulty it
entails.

**Comment by NullCase** [comment]
@molor 
Do what I did and pony up some money. Paper 1.13.1 already runs anti-xray for that reason.

**Comment by molor** [comment]
@NullCase, there is no ProximityHider in Paper. And me, for example, precisely this need..

**Comment by NullCase** [comment]
I'm sorry, it sounds like I was suggesting that you use Paper 1.13.1

My suggestion was that you pay someone to make the thing you want.

**Comment by NullCase** [comment]
@ProgrammerDan How much money would people have to pile up for you to produce Orebfuscator this week?

**Comment by ProgrammerDan** [comment]
@molor I appreciate the clear expression of urgency.

@NullCase At least on my end, weirdly perhaps, it's less about the money and more about the raw time, which is limited.

If I am able to get it done more quickly, and you or anyone feels those efforts (or the efforts of anyone who contributes to wrapping up the code update if someone submits a credible Pull request) are worthy of donation or contribution, do not hesitate to reach out to me or them about routes of donation at that point. 

As a maintainer of this project and creator of others, this work is generally done for the love and not the money, but as @NullCase has demonstrated money never hurts :).

I will do what I can to see if I can shift my priorities to work on this sooner, rather then later, but the constraint is largely external and not a reflection on my willingness or desire.

**Comment by Bezod** [comment]
Thank you for the hard work you do, we appreciate it. @ProgrammerDan

**Comment by ProgrammerDan** [comment]
Ok an update -- @SecurtyInsanity and I worked for a time on 1.13 update, but ran into some walls. Then, unexpectedly, @Aleksey-Terzi has reappeared and has made some incredible progress on a slightly different path towards 1.13. Once he posts his code, we'll be making a first 1.13 release. 

Should be soon, but we will slightly miss the end of September target timeframe. Hang tight! We're still on it!

**Comment by andfont** [comment]
Thanks for the incredible work you do, but is there any compiled version of the functional 1.13.1? Is there any prebuild? Will it really be updated? thanks friends but I'm hoping to have some functional compilation to finish migrating my server but I do not want to do it until I have it. if someone knows something communicate thank you!

**Comment by Aleksey-Terzi** [comment]
This branch contains workable version: https://github.com/DevotedMC/Orebfuscator/tree/mc1.13v2
You can also use my compiled version: https://www.dropbox.com/s/imweox3dvqmpehf/orebfuscator-4.4.1-SNAPSHOT.jar?dl=0

ProgrammerDan will do official release soon.

**Comment by andfont** [comment]
oooo THANK YOU THOUSAND THANKS FOR YOUR WORK was a very important complement very many thanks friends! I will try it as soon as possible xD but I repeat the community will thank you and very grateful!
