### ISSUE TITLE
error using 1.13.1 paperspigot

### ISSUE THREAD

**Issue by Gerolfing** [lishid/Orebfuscator#187]
map from 1.12 without upgrading, latest build of paper, nasty error.
java.io.IOException: No data to read.
[error.txt](https://github.com/lishid/Orebfuscator/files/2498412/error.txt)

**Comment by ProgrammerDan** [comment]
Hmm, definitely haven't tried on paperspigot -- few tips -- delete the orebfuscator_cache folder, be sure that Protocolib is updated to 4.4.0 or newer.

If you confirm those are done and still get these exceptions, let me know.

Thanks for opening the issue.

**Comment by ProgrammerDan** [comment]
@jordanwilliams1 Yeah -- Aleksey is aware of the issue and is working it
now. I'll do another point release once he has it licked. Thanks for
patience!

Thank you for reporting and confirming those steps @Gerolfing

**Comment by ProgrammerDan** [comment]
https://github.com/lishid/Orebfuscator/releases/tag/4.4.2 Please use this new release and let us know right away if the issues are not corrected @Gerolfing  @jordanwilliams1

**Comment by ProgrammerDan** [comment]
Haven't had any additional like-kind reports; closing this and related.
