### ISSUE TITLE
Errors spamming Spigot 1.13.1

### ISSUE THREAD

**Issue by AngieC233** [lishid/Orebfuscator#188]
Using these:-
Lastest version spigot 1.13.1
Orebfuscator 4.4.1
ProtocolLib #420

Errors spamming on console 
https://pastebin.com/F2BC2vn2

**Comment by ProgrammerDan** [comment]
Thank you for the report, we'll look into it -- which build of spigot
1.13.1?

**Comment by AngieC233** [comment]
This version for now, we update quite regularly.....[Mon, 22. Oct 2018 19:35:32 UTC INFO] This server is running CraftBukkit version git-Spigot-f6a273b-db10914 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)
[Mon, 22. Oct 2018 19:35:32 UTC INFO] Checking version, please wait...

**Comment by ProgrammerDan** [comment]
Thank you so much for confirming. Might be related to the prior issue, we will keep this open as we pursue.

**Comment by DmitryRendov** [comment]
confirmed on 1.13.2 as well... will try Aleksei's build

**Comment by ProgrammerDan** [comment]
fwiw working on official release build now, eta 15 mins or so

**Comment by ProgrammerDan** [comment]
Got all the releases published in all the places @AngieC233 @DmitryRendov -- https://github.com/lishid/Orebfuscator/releases/tag/4.4.2 -- please let us know if the problems continue

**Comment by AngieC233** [comment]
Thank you for the quick response and fixes.  Will let you know if the problems persist

**Comment by DmitryRendov** [comment]
4.2.2 works fine, thank you!
