### ISSUE TITLE
Error occurred while enabling Orebfuscator4 v4.4.2

### ISSUE THREAD

**Issue by Skajdrowski** [lishid/Orebfuscator#190]
Spigot: CraftBukkit version git-Spigot-e4d0c66-72c3617 (MC: 1.13.2)
ProtocolLib: 4.4.0
[latest.log](https://github.com/lishid/Orebfuscator/files/2523048/latest.log)

**Comment by ProgrammerDan** [comment]
Please share your config, as I'm seeing signs the config is pre-1.13 --
shouldn't cause a crash but will leave to things not obfuscating as
material names have changed.

We'll check out 1.13.2 and get back to you. Thanks for being the brave
first!
