### ISSUE TITLE
Block 3442 is absent in output palette.

### ISSUE THREAD

**Issue by DmitryRendov** [lishid/Orebfuscator#191]
Just an error on 1.13.2 - https://pastebin.com/2ctrHzYR
no idea, what's wrong. My world has been converted from 1.12.2.

git-Spigot-a1ba5fe-3359cb1 (MC: 1.13.2) 
Orebfuscator4 v4.4.2
ProtocolLib v4.4.0

Thank you!

**Comment by ProgrammerDan** [comment]
Thanks for the report!

**Comment by Skajdrowski** [comment]
@DmitryRendov Try to delete your config, it fixed my problem

**Comment by ProgrammerDan** [comment]
@DmitryRendov Any change?

**Comment by DmitryRendov** [comment]
cleared cache folder, no any incidents for couple of days in the server logs (using 4.4.2). Thank you for your support @ProgrammerDan 

Closed.
