### ISSUE TITLE
Fake blocks next to chests

### ISSUE THREAD

**Issue by Bobcat00** [lishid/Orebfuscator#199]
I'm seeing fake blocks underneath and behind chests.  It appears they are defined as non-transparent and should probably be transparent.  Orebfuscator 4.4.2, ProtocolLib 4.4.0, and CraftBukkit 1.12.2.

![2018-11-24_08 37 17](https://user-images.githubusercontent.com/3617206/48971247-1a254700-efe5-11e8-8bc4-cca331335c3d.png)

Split off the chunk boundary problem to #200

**Comment by ProgrammerDan** [comment]
Iirc you can turn water / flowing water / chests to be non-transparent, that will "fix" this.

**Comment by Bobcat00** [comment]
I think you mean to make them transparent.  But how?

**Comment by Bobcat00** [comment]
The /ofc tp command already lists water as transparent, so I don't understand why fake blocks are showing up next to it.  Chests are listed as non-transparent; I added chests to the config item Lists.TransparentBlocks, but it didn't change anything.  (Yes, I cleared the cache between tests).  So I'm totally confused now.

**Comment by Bobcat00** [comment]
I compiled the source from Github and was able to add CHEST, ENDER_CHEST, and TRAPPED_CHEST to the list of extraTransparentBlocks for my server version, and now Orebfuscator works properly.

It appears that the TransparentBlocks and NonTransparentBlocks config items are no longer used.

**Comment by ProgrammerDan** [comment]
Yeah, that was my worry. Must not be reading them in correctly, or I need to update the docs. I remember there were some issues getting the transparent lists rebuilt for 1.13 -- probably related. 

Thanks for the update -- I'll leave this open until I can get things in order upstream.

**Comment by Bobcat00** [comment]
I also discovered some visible fake blocks next to 'farmland' (tilled soil) blocks.  These blocks are 15/16ths of a block tall, so you can see the top edge of what's behind them.

**Comment by ProgrammerDan** [comment]
Good catch.

**Comment by cfi2017** [comment]
Has this been addressed yet?

**Comment by ProgrammerDan** [comment]
I've not yet found time. My apologies.

**Comment by Bobcat00** [comment]
Closing this because it's out of date.
