### ISSUE TITLE
Fake blocks next to transparent blocks on chunk boundaries

### ISSUE THREAD

**Issue by Bobcat00** [lishid/Orebfuscator#200]
I'm seeing fake blocks next to transparent blocks (water, glass, pressure plates) on chunk boundaries.  Orebfuscator 4.4.2, ProtocolLib 4.4.0, and CraftBukkit 1.12.2.

Split off from #199 because this is a separate problem.

![fakeblocks3](https://user-images.githubusercontent.com/3617206/48981698-05a98300-f0a7-11e8-87bc-9c1d1ad5e308.png)

**Comment by Bobcat00** [comment]
Closing this because it's out of date.

**Comment by ProgrammerDan** [comment]
Thanks for the cleanups.
