### ISSUE TITLE
A lot errors with latest spigot build

### ISSUE THREAD

**Issue by user127001** [lishid/Orebfuscator#203]
~1.5 log. I am better provide link to log than type it here
[latest.log](https://drive.google.com/file/d/1kZ0EkCNq48fgDAG6dn6hLGu1NNwAeqCf/view?usp=sharing)

Regards.

**Comment by ProgrammerDan** [comment]
Thanks, have a fix for this in test now

**Comment by ProgrammerDan** [comment]
Please download the latest release and let me know if this fixes the problem.

**Comment by kassadGLA** [comment]
Problem solved!
Thanks a lot.
