### ISSUE TITLE
Error occurred while enabling Orebfuscator4 v4.4.4

### ISSUE THREAD

**Issue by matbcvo** [lishid/Orebfuscator#224]
Error from server console: https://pastebin.com/raw/NR4DEKSs
Config file: https://pastebin.com/raw/RdwUE4vg

`[01:09:10] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-e5e5c7c-4e4cde4 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)`

**Comment by ProgrammerDan** [comment]
Appears to be a configuration loading problem due to old block names in
config. Please rename your config, and allow orebfuscator to regenerate the
base config. Then, layer in your changes to the new file, using the old
file as reference, but updating the material names.
