### ISSUE TITLE
Error while in use with Modern LWC

### ISSUE THREAD

**Issue by John-H-Smith** [lishid/Orebfuscator#241]
While using OFC with Modern LWC (https://github.com/pop4959/LWCX), locked chests can be opened if they are orebfuscated.

**Comment by NgLoader** [comment]
I check it out

**Comment by NgLoader** [comment]
Can you pls tell me which mc and ocf, lwc version your using

**Comment by John-H-Smith** [comment]
LWC Version: 2.1.3-87f48cb
Server version: git-Spigot-56f8471-43183ea
Orebfuscator 4.4.5

**Comment by John-H-Smith** [comment]
My LWC Version was out of date. Updating it fixed the issue.
