### ISSUE TITLE
java.lang.NoSuchFieldError: map

### ISSUE THREAD

**Issue by IITFA** [lishid/Orebfuscator#254]
This seems to happen a lot with the latest Orebfuscator and the suggested ProtocolLib. I don't know if this happened with previous versions as this is the first time running this with this setup. It "seems" like it might be working as the cache folder is populating. I have not tested it with an xray texture pack. Not sure what this error is, but it seems to happen when a player enters a new area.

https://pastebin.com/raw/2c6q2uJX

CatServer version git-CatServer-1.12.2-eb3ed0a (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2854)

ProtocolLib§f v§a4.6.0-SNAPSHOT-b482
Orebfuscator 4.4.4

EDIT: Not sure if related, but when caving, there are a LOT of "leftovers" from the obfuscation that only go away when you interact with the block.

**Comment by ProgrammerDan** [comment]
What version of MC is that? It seems that CatServer has removed or altered
the name of a particular field used via introspection in Orebfuscator
4.4.4. It may simply not work on that MC repackage without customization.

**Comment by NgLoader** [comment]
You can try this version: [Imprex Orebfuscator](https://www.spigotmc.org/resources/orebfuscator.82710)
