### ISSUE TITLE
plugin not loading

### ISSUE THREAD

**Issue by KiwiMCGaming** [lishid/Orebfuscator#256]
I have an externally hosted server. I shut down my server added the jar file into the plugins folder and started the server, tried this twice. Checked plugin list in Minecraft and read through console and it didn't load. checked plugin folder and no folder was created for it. I am running paperspigot 1.16.5

any way to fix this? my server hosts have tried different things and still no luck, and have ruled it down to the plugin itself.

**Comment by ProgrammerDan** [comment]
https://github.com/Imprex-Development/Orebfuscator

Please check out their efforts. This repo is not currently maintained.
