### ISSUE TITLE
Chunks doesn't load cuz of orebfuscator.

### ISSUE THREAD

**Issue by Mcdikmen** [lishid/Orebfuscator#257]
Hello,

I have a problem about a chunk load. It's not just about me, cuz all my players are facing this problem. If i remove the orebfuscator plugin, problem is resolving right away.

Waiting your comments.

Here is the video: https://youtu.be/SSziD_OmAhc

Thank u.

**Comment by NgLoader** [comment]
What ProtocolLib, Server and OFC version are you using?

Please use the latest ProtocolLib from his jenkins site

**Comment by Mcdikmen** [comment]
Using, ProtocolLib v4.6.1-SNAPSHOT-b498

Using, git-Paper-469 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

**Comment by NgLoader** [comment]
Try the latest version from [Imprex-Development](https://github.com/Imprex-Development/Orebfuscator/releases)

**Comment by Mcdikmen** [comment]
I am already using this version.
![image](https://user-images.githubusercontent.com/67418483/110845345-9548bf00-82bb-11eb-99e7-6f50f6606959.png)

**Comment by Mcdikmen** [comment]
Are you here ?

**Comment by ProgrammerDan** [comment]
I would recommend opening a related issue on the repository they linked you
to (as they manage and monitor that one much more closely).
