### ISSUE TITLE
Chunks doesn't load cuz of orebfuscator.

### ISSUE THREAD

**Issue by Mcdikmen** [lishid/Orebfuscator#258]
Hello,

I have a problem about a chunk load. It's not just about me, cuz all my players are facing this problem. If i remove the orebfuscator plugin, problem is resolving right away.

Waiting your comments.

Here is the video: https://youtu.be/SSziD_OmAhc

Thank u.

Using, ProtocolLib v4.6.1-SNAPSHOT-b498

Using, git-Paper-469 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)

OFC version 5.1.4

**Comment by ProgrammerDan** [comment]
Friend, you've merely recreated a new issue on the same repository.

Please go here: https://github.com/Imprex-Development/Orebfuscator/issues and open an issue there. Thank you!
