### ISSUE TITLE
world spaced name

### ISSUE THREAD

**Issue by FluffyDev1** [lishid/Orebfuscator#262]
When i put world name that contains spaces it's just crashes everytime i start the server

**Comment by ProgrammerDan** [comment]
Don't know that I've ever tried it with a world name with spaces, but
perhaps rename the world to be without spaces to avoid?

Other than that, go to https://github.com/Imprex-Development/Orebfuscator
with any issues, as they are actively developing. Thanks!

**Comment by FluffyDev1** [comment]
oh yea wrong repo, but still what if i can't rename the world to be without spaces?

**Comment by NgLoader** [comment]
Please open a issue on https://github.com/Imprex-Development/Orebfuscator

**Comment by NgLoader** [comment]
When you use the latest [Imprex-Development](https://github.com/Imprex-Development/Orebfuscator/releases) version it will work

**Comment by ProgrammerDan** [comment]
Awesome to hear, thanks @NgLoader
