### ISSUE TITLE
feature request: world-dependent obfuscation

### ISSUE THREAD

**Issue by ariehkovler** [lishid/Orebfuscator#35]
Would be good if obfuscation could be world-dependent; the obvious example would be obfuscate to smoothstone in the Overworld, netherrack in the Nether and Endstone in the End. 

Especially useful for proximity hider but possibly also for the new Nether-ores.

**Comment by ProgrammerDan** [comment]
This has been addressed; there is separate orebfuscation support for overworld and nether (although the end is not currently given special treatment to my knowledge).
