### ISSUE TITLE
problem with MCPC

### ISSUE THREAD

**Issue by vvswarhead** [lishid/Orebfuscator#37]
Hello! please solve incompatibility with MCPC, or how to use orebfusctor in MCPC ?

**Comment by Sirse** [comment]
@ProgrammerDan, @Aleksey-Terzi is there any chance for Cauldron/Thermos support?
Many servers still using it, and staying unprotected from cheaters.
Now exist workable abandoned fork - https://github.com/joserobjr/Orebfuscator/tree/cauldron-4096-read-only, with correct mappings, but author not implement extended-id support.

**Comment by RoboMWM** [comment]
@Sirse Cauldron/Thermos are 1.7, and Orebfuscator (at least this repo) is only supporting 1.9 and above.
