### ISSUE TITLE
stone damage values for obfuscated chest?

### ISSUE THREAD

**Issue by ariehkovler** [lishid/Orebfuscator#41]
Stone-Obfuscated chests seem to show stone with a damage value rather than 'natural' stone, making it possible to detect them using custom clients. 

In 1.8+, damage values of stone are also used for the alternative stone types.

**Comment by ariehkovler** [comment]
Does proximity obfuscation work in the 1.8-compatible builds?

**Comment by lishid** [comment]
Latest version should have fixed it. This also fixes the damage value potential vulnerability.
