### ISSUE TITLE
Ghost blocks

### ISSUE THREAD

**Issue by drjawa** [lishid/Orebfuscator#52]
Using the latest version of spigot 1.8.3 and protocolib along with latest available orebfuscator.

Getting lots of complaints about ghost blocks, blocks that don't exist that appear and disappear randomly. Additionally, if user has render distance set higher than server render distance, they report seeing ghost pillars at the edge of the chunks that disappear as they move closer to them. Removing orebfuscator seems to make these go away.

We are using engine mode 1 (no spoofing).

If you need any other information, let me know, thanks.

**Comment by danquist** [comment]
Can you comment on how these were fixed?
