### ISSUE TITLE
Please help!!

### ISSUE THREAD

**Issue by MrBeefchop** [lishid/Orebfuscator#56]
By my server the ores disappear if I rightclick sometimes and you can bug in there..
Spigot 1.8.3
Plugin: 3.0.5

And TNT Blocks are spawning randomly on the Map and if I rightclick them the change to stone..
And Anti-Xray Protection is working, but with this buggs..

No Errors!

Config: http://pastebin.com/AAXGZpnf

**Comment by ProgrammerDan** [comment]
Are you still experiencing these issues or in need of support?
