### ISSUE TITLE
Error in console on startup

### ISSUE THREAD

**Issue by HollishKid** [lishid/Orebfuscator#57]
Hello,

This is my first time installing Orebfuscator (v3.0.5) on my server. I get the follwing issue in console ...
Any ideas what I'm doing wrong?

http://pastebin.com/Af3jdhDF

Thanks in advance for your help,

Hollish

**Comment by ProgrammerDan** [comment]
Will be addressed along with #69

**Comment by ProgrammerDan** [comment]
If you still need one, check the [Legacy] tagged releases here: https://github.com/lishid/Orebfuscator/releases
