### ISSUE TITLE
Obfuscate Signs

### ISSUE THREAD

**Issue by ProgrammerDan** [lishid/Orebfuscator#65]
This is likely (won't fix) and as such I closed it, but for reference it would be good to investigate if sign obfuscation is now possible:

http://dev.bukkit.org/bukkit-plugins/orebfuscator/tickets/111-proximity-hider/

**Comment by Bedah95** [comment]
After using Proximity-Hider on signs, I recogniced they are empty when they become visible again.

Reloading chunk doesn´t help, is there a known fix?

**Comment by Aleksey-Terzi** [comment]
Bug is fixed - both wall sign and standing sign are now obfuscating correctly using ProximityHider.
Fix will be available in the next release.
