### ISSUE TITLE
Limit Cache Size

### ISSUE THREAD

**Issue by ProgrammerDan** [lishid/Orebfuscator#66]
http://dev.bukkit.org/bukkit-plugins/orebfuscator/tickets/117-reduce-orebfuscators-used-space/

Could be useful -- allow limit to be set for cache, where if exceeded old cache entries are "aged out", with best-effort to keep size of cache under threshold.

**Comment by MegaNarwhal** [comment]
I currently have a script run daily that deletes cache files that haven't been accessed for over a week. This keeps the cache at a sane size based on what areas of the map are actually used frequently. If disk space is really limited, the cache might not be worth using if OFC needs to delete and recreate cache files repeatedly.

**Comment by ProgrammerDan** [comment]
That's awesome. Cron script? Feel free to share the pastebin if you want to!

**Comment by MegaNarwhal** [comment]
It's a one-liner: ``find ~/server/orebfuscator_cache -type f -name '*.mcr' -atime +7 -delete``
``-atime`` could be changed to ``-mtime`` if it's preferable to delete cache files that haven't been modified rather than accessed; the former normally ends up deleting more cache files.

**Comment by ScuroK** [comment]
@MegaNarwhal Can you explain me how to use this script?
I never used any scripts before so i dont know how to install it.

**Comment by EvilOlaf** [comment]
This works only on *nix based hosts and you need shell access.
Add the script to your crontab if you want to run it scheduled.

**Comment by ScuroK** [comment]
:( okay...

**Comment by ScuroK** [comment]
It would be awesome to have a config option to clear the cache after X days!

**Comment by RoboMWM** [comment]
@ScuroK, this isn't something hard to do on Windows or any other platform. Now, I could understand if you have a shared host, but even then you could have something on your own computer operating via FTP every so often.

**Comment by ScuroK** [comment]
hmmm idk how i can do it.. maybe i search for a command scheduler plugin

**Comment by Aleksey-Terzi** [comment]
@ScuroK
I'm agree with RoboMWM - this could be implemented on Windows too, for example using scheduled jobs and PowerShell.
But I will look into this problem and will try to implement this in Orebfuscator, this at least will allow to close this issue :)

**Comment by ScuroK** [comment]
Thank you! It would be a blessing to have this option.

**Comment by ProgrammerDan** [comment]
@Aleksey-Terzi for Implementation, what configuration option controls it?

**Comment by Aleksey-Terzi** [comment]
New configuration option "DeleteCacheFilesAfterDays".  
Default value is 0 which means that this feature is disabled.

Also information about this option have been added to the wiki.

**Comment by ScuroK** [comment]
Sounds awesome! Can i have the jar file for testing? <3

**Comment by Aleksey-Terzi** [comment]
Sure, file compiled by me is here: https://www.dropbox.com/s/6eozk0gfplmxtua/orebfuscator-4.1.10-SNAPSHOT.jar?dl=0

Let me know if any problems.

**Comment by ScuroK** [comment]
Thank you!
