### ISSUE TITLE
Want Orebfuscator on my Jenkins server?

### ISSUE THREAD

**Issue by PaperSpigot** [lishid/Orebfuscator#70]
I noticed you don't have any development builds on your README.md so I decided to add it to my Jenkins. Here's my [CI server](https://ci.terrocidepvp.net/). I've also got a [Maven repo](http://repo.terrocidepvp.net/artifactory/jenkins/). If you want me to change this or if you aren't alright with this, please let me know. :smile:

**Comment by ProgrammerDan** [comment]
Haha! It's on my todo list. If you're okay with giving Aleksey and I administrative access/control over the Orebfuscator project, I'd be happy to advertise its presence there, at least until I can get Devoted's up and running and public.

**Comment by HunterGPlays** [comment]
Sure, just sign up on my Jenkins and give me your usernames.

-----Original Message-----

**Comment by ProgrammerDan** [comment]
I've signed on as, predictably, ProgrammerDan.

**Comment by HunterGPlays** [comment]
I've given you access to build, cancel running builds and modify the build description. If you need any other perms (such as modifying the repo info/maven params) just let me know, although I doubt this would be needed.

**Comment by ProgrammerDan** [comment]
Thanks, I'll let you know for the other attributes.

**Comment by ssamjh** [comment]
Do you by any chance need a build server again, as it seems the OP's one is no longer online.

**Comment by ProgrammerDan** [comment]
We recently acquired one: https://build.devotedmc.com/job/Orebfuscator-master/

I keep forgetting to update the linkages to point to it, thanks for the reminder. Also, I need to get the build triggers set up as currently it only builds when manually triggered.

**Comment by PaperSpigot** [comment]
All my sites are dead as I'm not really into MC anymore. Since you've got one of your own CIs, I'll consider that suitable grounds to close this issue.
P.S. for build triggers, I'd recommend getting the thing where it polls the .git link every 5 mins or so and builds if it's changed. That's easier than using the GitHub integration but it's really up to you.

**Comment by ProgrammerDan** [comment]
Yep, thanks again for the builds "in the meantime" :). Good luck with your future ventures.
