### ISSUE TITLE
Add / remove worlds from obfuscate using command is non-functional

### ISSUE THREAD

**Issue by ProgrammerDan** [lishid/Orebfuscator#73]
As reported: command /ofc disable/enable worldname don't work
by @Belfedia

We'll check it out, thanks.

**Comment by Aleksey-Terzi** [comment]
I've just tested enable and disable function with Nether and it works ok.

So what maybe happened:
1. Make sure command syntax is correct. For example if I want to disable world with name **world_nether** then following command should be used: **ofc disable world world_nether**
2. After command applied - client should refresh chunks (for example just relogin)

**Comment by Aleksey-Terzi** [comment]
@Belfedia if you anyway have problems with world enabling/disabling then please reopen issue and provide details.
