### ISSUE TITLE
Random blocks randomly appearing for users

### ISSUE THREAD

**Issue by Liphius** [lishid/Orebfuscator#75]
Here's an example from my player. Clearing the cache and telling them to relog fixes this, but it's annoying to do every time as there's complaints about this plugin being "no good" if it does this, which of course is untrue but players are always right haha.

here's the image:
http://i.imgur.com/2NSv7m7.png

The player was not in a cave or anything, they were in an open place with a tiny opening to a tiny hole that had stone everywhere and those blocks appeared.

edit: another report from a player, this time with lava. you can see the random blocks beside it in the corners. http://i.imgur.com/dPfKoBc.png http://i.imgur.com/XT0QpBK.png

There's also ores appearing when mining but when the user gets closer to it, it turns into a stone (as it was stone originally but Orebfuscator shows an emerald ore there, not sure how to fix this/turn it off)

Not sure if there's something wrong with my configuration:

https://gist.github.com/Liphius/b20cf741e25f1ea302d79754d0a204d3

**Comment by ProgrammerDan** [comment]
It'll be a bit more processing expensive and provide a tiny bit less defense against x-rayers, but try increasing your update radius to 3 or 4. In the past where I've encountered similar, the update radius is often to "blame"... however, @Aleksey-Terzi will know better then I based on the new design.

**Comment by Liphius** [comment]
Okay, i'll try that for now and see if it helps.

**Comment by Liphius** [comment]
Hmm, they still keep appearing for a split second when mining, and i saw like a line of those random blocks when I world edited out a small hole.

no luck i guess :(

**Comment by ProgrammerDan** [comment]
We'll have to wait for Aleks to comment :).

I do recall seeing that earlier versions of orebfuscator do not respond to world edit events; the chunk cache won't be recomputed by world edit interactions, so you'd have to force a chunk reload (log out/in or leave view distance and return) for those artifacts to disappear.

**Comment by Liphius** [comment]
Okay, but what about the random blocks replacing stone when breaking the stone blocks?

they appear less than a second and can be a pain when mining.

But sure, i'll wait for the response! thanks for the help so far :)

**Comment by ProgrammerDan** [comment]
That's the onbreak update taking a moment - I'm guessing it lags behind the speed at which the tool can break. See my issue here: #67 .

What kind of tool do you use to test breaking? I'm guessing Efficiency 5?

**Comment by Liphius** [comment]
Ah, i used creative when testing that, so probably similar speed to your issue.

**Comment by ProgrammerDan** [comment]
One other thing you might try is using Engine mode 1 -- this will "obfuscate" with just stone instead of random blocks. At the very least, when an ore pops into view in this mode, it will actually be a real ore. It might work a bit better (but does "protect" less).

**Comment by Aleksey-Terzi** [comment]
> here's the image:
> http://i.imgur.com/2NSv7m7.png
...
> There's also ores appearing when mining but when the user gets closer to it, it turns into a stone (as it was stone originally but Orebfuscator shows an emerald ore there, not sure how to fix this/turn it off)

Looks like Dan already answered about this issue.
I'm agree with his proposed workaround - use Engine Mode 1.
About real fixing of problem - I need to do some testing and then I will provide response (this could take some time).

> edit: another report from a player, this time with lava. you can see the random blocks beside it in the corners. http://i.imgur.com/dPfKoBc.png http://i.imgur.com/XT0QpBK.png

This bug will be fixed in the next release.

**Comment by RoboMWM** [comment]
Yea, either setting initial radius a bit higher or using mode 1 will have to be the case for now:

https://youtu.be/XSb39HppwXs?t=3m44s

**Comment by ProgrammerDan** [comment]
@Liphius Grab the latest release, let us know if the lava issue still exists on that release level (4.0.7)

**Comment by Liphius** [comment]
Appears to be fixed. Same player that had the issue says the issue is gone.

Great job on the update!

**Comment by ProgrammerDan** [comment]
Perfect. We'll continue to chip away at the performance problems :)

**Comment by RoboMWM** [comment]
Hmm, I wonder if considering lava as an opaque block would be much of an issue for xray mode 1. If anything, it'd provide more protection for ores adjacent to lava that would normally be visible otherwise.

**Comment by ProgrammerDan** [comment]
@RoboMWM  I might be wrong but I _think_ you can control it server-side by changing a line in the transparent_blocks.txt file -- just set minecraft:lava to false instead of true -- then lava will be "opaque" again.

**Comment by Aleksey-Terzi** [comment]
Yes this is true block "transparency" could be controlled through file "orebfuscator-4.0.7-SNAPSHOT.jar\resources\transparent_blocks.txt"
I'm guessing it would be good to expose this file to plugin's config folder and allow to customize, but not sure.
As another solution - we could have different "transparency lists" for mode 1 and mode 2.

**Comment by ProgrammerDan** [comment]
Please update to [v4.0.9](https://github.com/lishid/Orebfuscator/releases/tag/v4.0.9) and reopen this issue if the first reported problem doesn't resolve.
