### ISSUE TITLE
update-radius greater than 3 does not deobfuscate blocks

### ISSUE THREAD

**Issue by RoboMWM** [lishid/Orebfuscator#76]
Is `AntiTexturePackAndFreecam` supposed to do this? Seems to only happen when mining stone.

https://youtu.be/SOYPwPJkBOQ

(Was in gamemode 3 with night vision potion.)

**Comment by Aleksey-Terzi** [comment]
When AntiTexturePackAndFreecam is enabled (it enabled by default) - it adds random air blocks instead of normally obfuscated blocks.
In all other - it works exactly the same as usual obfuscated block.
This means that when you are breaking block - nearly placed obfuscated blocks are deobfuscating.

**Comment by RoboMWM** [comment]
It actually seems to be working more like proximityhider, since it's updating a nearby chunk instead of a nearby radius, at least for this as it seems... Or wait - when it updates radius, it's actually sending an entirely new chunk to the client..? And hence why the air blocks are changing each time a block is broken..?

**Comment by Aleksey-Terzi** [comment]
No, AntiTexturePackAndFreecam is not using ProxmityHider or any helpers, this is pure obfuscation.
And no - it is not sending new chunk to the client (or at least should not send :) )
I've tried both xray resource pack and xray mod and cannot reproduce problem.
I've added logging to the plugin - it is not sending new chunk while another player is breaking blocks.

Is it possible that blinking somehow related to texturepack you using?

I propose to make the following experiment:
1) switch plugin to Engine Mode 2
2) try to mine with player 1 while player 2 is looking using xray mod - if chunk is reloading then random blocks should change

**Comment by RoboMWM** [comment]
I'm using vanilla texture pack and `/gamemode 3` to observe this. I'll try to test with engine mode 2.

**Comment by Aleksey-Terzi** [comment]
I've tried gamemode 3 and cannot reproduce blinking as well.
Not sure what this was in your example, but I'm guessing if it would reloaded chunks everytime when another player broken block - then I think it would lagged very significantly.

It would be good if you can try obfuscator engine mode 2 + gamemode 3 and let me know if you see any problems.

**Comment by ProgrammerDan** [comment]
@RoboMWM Any update? Or are we good to close?

**Comment by RoboMWM** [comment]
Haven't had time to test unfortunately, but I have it on my todo list (especially since I need another player and to switch config settings.)

**Comment by RoboMWM** [comment]
Oh ok, doesn't seem to be the entire chunk, but I guess it's also changing the obfuscated blocks around the player... shouldn't it be revealing the proper locations to the player instead of just re-obfuscating? Looks like this: https://youtu.be/bFXg1Qjda-Y and with server-side "xray" enabled, for clarity: (upload pending)

**Comment by RoboMWM** [comment]
From the above video it doesn't seem like it's actually de-obfuscating according to the `UpdateRadius`... In fact, I don't even need a fast pickaxe to see blocks appearing while in engine mode 2. http://i.imgur.com/552drr3.png

Instead of deobfuscating the blocks in the updateradius, it's instead just re-obfuscating blocks in this radius...

**Comment by Aleksey-Terzi** [comment]
Thanks for details, I will look this later and then provide response.

**Comment by Aleksey-Terzi** [comment]
> From the above video it doesn't seem like it's actually de-obfuscating according to the UpdateRadius

Yes, I see - it definitely reloading chunk.
Btw this could be related to a lot of block updates.
Recently I walked through Spigot code and found that it is doing chunk reload for players if number of block updates > 64. With UpdateRadius = 4 this number could be reached by 3 - 4 block breaks.
But I need to investigate this more detailed.

> Instead of deobfuscating the blocks in the UpdateRadius, it's instead just re-obfuscating blocks in this radius...

Ok, I will investigate this more detailed.

**Comment by RoboMWM** [comment]
https://gist.github.com/RoboMWM/0b238c9c0849389b7bacd867ae8ec5ff

I set `update-radius` high to account for player latency, but if I can't do that I suppose I'll have to reduce it.

**Comment by RoboMWM** [comment]
Changed `update-radius` to 3 along with using the 1.9.4 version, and it doesn't blink as it does in the video. So I guess that happens only with large update radii?

**Comment by Aleksey-Terzi** [comment]
> So I guess that happens only with a large update radius?  
    
Yes, looks like this is related to issue I've described above (server is doing full chunk reload instead of block changes).  

But not yet looked into this problem more detailed.
Now is trying to fix some issues related to 1.9.4

**Comment by Aleksey-Terzi** [comment]
Sorry for long delay with answer.

Just tested today:

1) When UpdateRadius = 2 - this is forcing to update 25 blocks per 1 block break when digging down

2) When UpdateRadius = 3 - this is forcing to update 60 blocks per 1 block break when digging down

3) When UpdateRadius = 4 - this is forcing to update 125 blocks per 1 block break when digging down. This is actually forcing MC to do chunk update (as I told if there are at least 64 block updates - MC is doing chunk update) - we see this is in your video and I see this is in my test logs.

Conclusion:

1) Any value for UpdateRadius higher than 3 will usually do the same - force MC to update chunk.
Therefore it makes no sense to set UpdateRadius to value higher than 4.
But don't forget that there are could be different situations like part of block updates will go to one chunk and another to another chunks (in this case chunk maybe not forced to resend) and like there are could be a lot of transparent blocks and therefore number of update blocks could be much less.

2) When UpdateRadius <= 3 then for the case with one player-miner it will not force chunk to resend, but will do block updates.

3) According to what was said above and that you saw issue only with UpdateRadius = 4 then behavior shown in the video is correct.

Please let me know if you have more questions.

**Comment by RoboMWM** [comment]
I guess adding this info to the wiki would be helpful (I would but on mobile right now). Thanks for the info!

**Comment by Aleksey-Terzi** [comment]
> I guess adding this info to the wiki would be helpful (I would but on mobile right now).

Yes, agree.
I will do this.
