### ISSUE TITLE
Tps drop while mining with high eff pic

### ISSUE THREAD

**Issue by jordanwilliams1** [lishid/Orebfuscator#80]
So my server allows players to have eff 6-10 pics, When i was mining with a eff 10 pic my tps dropped from 20 to 19.20. Is there anyway to optimize this plugin so if someone with a high eff pic mines loads of blocks it doesn't lag the server?

My current config: http://hastebin.com/qonabanife.cpp

**Comment by jordanwilliams1** [comment]
Also notice Orebfuscator cause's lag for 1-3 seconds when a player joins the server or if a players dose /rtp it lags very very slightly but this would become a problem for servers with 60+ people online  :(

**Comment by RoboMWM** [comment]
From 20 to 19.2. That's not a huge concern. Either way, if you're worried, please provide a timings report. Also check out the wiki for suggestions on reducing CPU usage: https://github.com/lishid/Orebfuscator/wiki/How-to-properly-configure-Orebfuscator#resource-point-of-view

**Comment by ProgrammerDan** [comment]
@jordanwilliams1 I'm going to close for now -- be sure to update to [v4.0.9](https://github.com/lishid/Orebfuscator/releases/tag/v4.0.9) which contains numerous fixes and improvements. Reopen if the performance issues persist.
