### ISSUE TITLE
Air blocks

### ISSUE THREAD

**Issue by jordanwilliams1** [lishid/Orebfuscator#81]
Air blocks are becoming a problem for me on my server, How do i disable air blocks in the anti xray? So i set   AirGeneratorMaxChance: 0 ?

**Comment by Aleksey-Terzi** [comment]
If you about random air blocks - you can disabled it by setting AntiTexturePackAndFreecam to false.

**Comment by RoboMWM** [comment]
I'm curious as to how they're a problem for you. Perhaps show us a video and/or screenshot of what problem it causes?

**Comment by jordanwilliams1** [comment]
Its causing a problem because the player is mining with a 3x1 pic and the plugin only sees them mining 1 block. If you could just make a option to disable air block that would b great?

https://youtu.be/cUSUA07Q2cA

Using: http://dev.bukkit.org/bukkit-plugins/powermining/

**Comment by RoboMWM** [comment]
Ah, you're using another plugin, that's useful information. Tell the powermining devs they need to fire a blockbreakevent for the blocks they're breaking. As a temporary fix, disable `AntiTexturePackAndFreecam` in the config.

**Comment by ProgrammerDan** [comment]
Closing for now as it is addressable through an existing configuration option. Thanks!
