### ISSUE TITLE
Orebfuscator cause lag on playerlogin or if they tp

### ISSUE THREAD

**Issue by jordanwilliams1** [lishid/Orebfuscator#82]
Orebfuscator cause's lag for 1-3 seconds when a player joins the server or if a players dose /rtp it lags very very slightly but this would become a problem for servers with 60+ people online.

My tps dropped from 20 to 18 when someone joined... Orebuscator causes the server lag when it has to render all them chunks? Can we get a fix for this:

tps drop proof:(
https://gyazo.com/466acfd083ce4b7232dd56fc4d77a951

**Comment by RoboMWM** [comment]
Please provide a timings report. Also see the wiki for suggestions on how to reduce CPU usage. https://github.com/lishid/Orebfuscator/wiki/How-to-properly-configure-Orebfuscator#resource-point-of-view

**Comment by ProgrammerDan** [comment]
TPS is generally a running average -- point in time measurements are interesting, but never conclusive. As @RoboMWM says, we'd need your timings, run for about an hour, to get any kind of usable data. 

At least on my server there is no Orebfuscator related problems on join -- plenty of our other plugins do poorly there, and they show up on timings for me to tsk at all the time :D.

**Comment by jordanwilliams1** [comment]
Here's my timings of the lag when a player tp's to a random place: https://timings.aikar.co/v2/?id=9156d19e43dc46fb8953390a089e4b7e&section=lag

**Comment by RoboMWM** [comment]
We're going to need more than just 15 seconds of timings.

**Comment by jordanwilliams1** [comment]
It comes under Minecraft::world - chunkLoad - Structures

Since I added this plugin thats become high :(

**Comment by ProgrammerDan** [comment]
Please run timings for about 30 minutes, if you want teleporting often during that period. 15 seconds, sadly, tells us very very little.

Thanks.

**Comment by ProgrammerDan** [comment]
Lacking any longer term timings, I can't be confident that Orebfuscator is involved in the lag here. Please update to [v4.0.9](https://github.com/lishid/Orebfuscator/releases/tag/v4.0.9); if the problem appears to persist, run timings for 30 minutes or more, reopen this issue and paste the timings.

thanks!
