### ISSUE TITLE
Error when swaping items in the left hand

### ISSUE THREAD

**Issue by NewBestX** [lishid/Orebfuscator#87]
Looks like there is an error showing up in the console every time I put an item in the left hand.
Using spigot 1.9.2 .

http://pastebin.com/na2mTJPU

**Comment by ProgrammerDan** [comment]
This looks like a problem with ProtocolLib, actually -- can you open an issue on their repository -- https://www.spigotmc.org/resources/protocollib.1997/

It's possible it's been addressed, make sure your ProtocolLib is updated to latest.

**Comment by RoboMWM** [comment]
https://www.spigotmc.org/resources/protocollib.1997/

Says to use 4.0.0, which you can get from the linked build server, or wait until tomorrow when he releases it on spigot.

**Comment by Aleksey-Terzi** [comment]
According to logs on the server is used ProtocolLib 3.7.0, I strongly recommend to use latest version: http://ci.dmulloy2.net/job/ProtocolLib/lastStableBuild/

I think this will solve the problem.

**Comment by ProgrammerDan** [comment]
Closing this and its duplicate, @NewBestX please reopen if, after updating to Protocollib 4.0.0 the issue continues.
