### ISSUE TITLE
Extra Data for a Block Sometimes Will Lost 

### ISSUE THREAD

**Issue by connection-lost** [lishid/Orebfuscator#90]
After updating to 4.0.11, there is a notable issue that extra data for a block will sometime lost. For instance, the text will disappear on sign, the skull will always show a default skeleton head.

This seems to be only affecting the first player who see the sign/skull for the first time. The second time another player get into the range.

### Example Reproduce & Results
1. Start the server
2. Think about some place that has signs.
3. Let a player teleport there. The player will not able to see texts on sign.
4. Let another player come to the same place. The other player will see text on sign.
5. Let the first player log out then log back in. Both players are able to see text on sign.

### Other
Config: http://pastebin.com/njGgctKK
Sometimes, if my client is not reacting fast enough, the first player that get to the area for the first time will see the text on the sign for a brief second, then the text disappears. Not sure this will help with anything.

### Affected Version:
Since 4.0.11.
4.0.10/9/7/5 are all tested and seems to be not affected.

**Comment by RoboMWM** [comment]
Config? I'm assuming this is proximityhider related

**Comment by connection-lost** [comment]
Sorry I should have posted my config...
http://pastebin.com/njGgctKK
Note: The proximity hinder is disabled

**Comment by Gnarman** [comment]
I also have this issue.
http://pastebin.com/Vc7tZwab

This is my config, which also has proximity hider disabled

**Comment by Aleksey-Terzi** [comment]
Thanks for bug reports.
Both issues #90 and #91 are fixed and fix will be available for next release.

**Comment by ProgrammerDan** [comment]
Closing for now; after updating to 4.0.12 release, if the issue remains please re-open this ticket.
