### ISSUE TITLE
Animals are invisible to players

### ISSUE THREAD

**Issue by Gnarman** [lishid/Orebfuscator#91]
http://pastebin.com/Vc7tZwab

This is my config.

Players have reported that their animals are invisible, even when they are right next to them and in well-lit areas.

Using version  4.0.11 and Spigot version git-Spigot-e6f93f4-935f18b

**Comment by ProgrammerDan** [comment]
Just to be sure -- you've confirmed that by disabling Orebfuscator, the issue also goes away?

**Comment by Gnarman** [comment]
Yes. I initially restarted the server, but the issue persisted. Upon removing Orebfuscator and restarting again, the problem went away.

**Comment by ProgrammerDan** [comment]
Ok thanks! We'll try to reproduce.

Just vanilla animals, or any other special config situations we should note besides the given orebfuscator config?

**Comment by Gnarman** [comment]
No problem, let me know if there's any extra info I can supply.

This is just vanilla animals. It happened with cows, sheep and chickens. As far as I know that is all. If it helps, these animals were all in player-built farms. You'd see the animal particles, for example you'd see splashing from the chickens if they were in water, but not the chicken itself.

There shouldn't be any extra configs that would affect it, as far as I know.

**Comment by ProgrammerDan** [comment]
Ok -- last question for now :).

Do you notice any errors in the server log? Any errors about parsing packets or other issues like that? And just to be absolutely sure, you're running ProtocolLib 4.0.0 or newer?

Thanks!

**Comment by Gnarman** [comment]
No errors at all, not even at startup.

This is the ProtocolLib version: ProtocolLib version 4.0.0-SNAPSHOT-b266

**Comment by ProgrammerDan** [comment]
Alright, thanks for the extra details.

**Comment by ProgrammerDan** [comment]
Upgrade to 4.0.12 and let us know if the issue remains by reopening this ticket.
