### ISSUE TITLE
1.9.4 compatibility

### ISSUE THREAD

**Issue by WolfezzKyne** [lishid/Orebfuscator#92]
Huge errors on block break event on 1.9.4 (craftbukkit and spigot)
http://paste.md-5.net/qekewimaga.avrasm

**Comment by ProgrammerDan** [comment]
We do not yet support 1.9.4 -- it uses a new revision of NMS. Keep an eye out for a future release supporting that version.

**Comment by Phreag** [comment]
How soon are you planning to do this update?

**Comment by ProgrammerDan** [comment]
I will be doing an initial release today.

**Comment by ProgrammerDan** [comment]
Full support forwards and back along the 1.9.x path is now secure in release 4.0.14
