### ISSUE TITLE
Blocks constantly changing?

### ISSUE THREAD

**Issue by ryantheleach** [lishid/Orebfuscator#97]
I notice in some of the gifs used that whenever a block is broken / updated, the data sent seems to be randomzied, couldn't people just scan to see what ores don't change? Or is this an old flaw that has been fixed?

In addition, I believe that the constant changing of blocks (especially if air is included, to prevent camming) can cause client performance problems.

I do admit however it has been a long time since I last used / tested / hosted a server let alone one with Orefuscator, so please forgive me if this has long been fixed.

I believe that it should be pretty easy to stop it from constantly changing, if you use a seeded randomization based on chunk co-ordinates and a server specific secret. That way, no matter what changes the blocks that need to be updated and sent to the client are the same as the existing blocks, causing less calculations to be performed as it's received the same data that was already there, in addition as the air is no longer changing / moving around the cached calculations in the client don't need to be reupdated constantly.

**Comment by RoboMWM** [comment]
Are you referring to my issue? Because mine was a bug and not the way it is intended to work. As for randomization, iirc the cache should provide that sort of information.

**Comment by ryantheleach** [comment]
I think I may have inadvertantly thought that the random changing from the videos is how the plugin worked, if the cache was introduced since I last used it, that may explain it.

One thing I'd like clarification on, is why a cache vs using a seed? doesn't it consume a lot more memory?

**Comment by RoboMWM** [comment]
Well the point is to not recalculate the obfuscation and then sending chunks. Though there's discussion of it in another issue: https://github.com/lishid/Orebfuscator/issues/66. 

Also, from the video you most likely saw from my issue, please note later down that I mentioned it stopped occurring after moving values back closer towards default (and the potential issue is explained in the issue as well): https://github.com/lishid/Orebfuscator/issues/76#issuecomment-219359056

**Comment by Aleksey-Terzi** [comment]
@ryantheleach

Blocks are updating only when player is digging and Orebfuscator is updating only blocks around brocken block.
How much it is updating is depends on UpdateRadius value.
If there are 64 or more blocks to update - then MC instead of block updates is resending chunk to players.
More info you can find in discussion for issue #76 (especially at the bottom).

Since this issue is mostly duplicating issue #76 then I'm closing it.
