### ISSUE TITLE
Dropped items appearing as stone?

### ISSUE THREAD

**Issue by austin652** [lishid/Orebfuscator#99]
When you drop any item from your inventory on the ground it would appear as stone and not as the actual item it should be and if you pick it up it's the correct item it should be. I am using version 4.0.14 for 1.9 1 on spigot 1.9.2 and an untouched config file, on a side note I since updated to 1.9.4 and plugin version 4.0.12.1 (1.9.4) and the problem seems to be gone.

**Comment by ProgrammerDan** [comment]
As far as I've been able to determine, this is a clientside issue. I've noticed it from time to time in 1.9 clients predating the update of Orebfuscator to support 1.9. 

That said I might be missing something, so I'll leave this open for Aleks to investigate.

**Comment by RoboMWM** [comment]
Not an orebfuscator issue. https://bugs.mojang.com/browse/MC-93454

**Comment by austin652** [comment]
It only happened with orebfuscator installed. when I removed it, the blocks were correct when dropped again. when I re-added it the were incorrect

**Comment by RoboMWM** [comment]
Not the case for me, just saw it happen on one of my servers where I don't have Orebfuscator installed.

**Comment by Aleksey-Terzi** [comment]
My guess is that this issue could be related to lags and how client is trying to process this.
Just yesterday seen exactly this issue on PvP server (it lagged significantly for person who played) which is not supposing mining or building and therefore seems not have Orebfuscator.
Also I was able to see similar issue previously on different servers - during fast mining broken block for short period of time is shown as stone.

@austin652
Is it possible for you to provide more details about configuration of your server and connection quality for client you used for testing?  
Also I would appreciate if you can try your server's configuration on some environment where possibility of lags is very low (client and server on the same comp with just Orebfuscator and no other plugins?)

**Comment by austin652** [comment]
I can do that

**Comment by austin652** [comment]
Ok, I did the test with just Orebfuscator 4.0.14 and spigot 1.9.2 with client and server on the same comp and the issue mentioned was not reproduced. the configuration is the same because on both servers I left the config as it came by default. I did nothing different except having no other plugins installed.

**Comment by Aleksey-Terzi** [comment]
Thank you for testing.
I'm supposing issue is solved and therefore I'm closing it.
